
out <- function(path = "tools/debug/", fileName = "R_Log.txt") {
  
  con <- file(paste0(path, fileName), open = "w")
  writeLines("termu", con)
  writeLines(paste(sprintf("%.3f",termu), collapse = "     "), con)
  writeLines("terml", con)
  writeLines(paste(sprintf("%.3f",terml), collapse = "     "), con)
  writeLines("scalcoefl", con)
  writeLines(paste(sprintf("%.3f",scalcoefl), collapse = "     "), con)
  writeLines("scalcoefu", con)
  writeLines(paste(sprintf("%.3f",scalcoefu), collapse = "     "), con)
  writeLines("firb", con)
  writeLines(paste(sprintf("%.3f",firb), collapse = "     "), con)
  writeLines("firg", con)
  writeLines(paste(sprintf("%.3f",firg), collapse = "     "), con)
  writeLines("firi", con)
  writeLines(paste(sprintf("%.3f",firi), collapse = "     "), con)
  writeLines("firl", con)
  writeLines(paste(sprintf("%.3f",firl), collapse = "     "), con)
  writeLines("firs", con)
  writeLines(paste(sprintf("%.3f",firs), collapse = "     "), con)
  writeLines("firu", con)
  writeLines(paste(sprintf("%.3f",firu), collapse = "     "), con)
  writeLines("fsena", con)
  writeLines(paste(sprintf("%.3f",fsena), collapse = "     "), con)
  writeLines("fseng", con)
  writeLines(paste(sprintf("%.3f",fseng), collapse = "     "), con)
  writeLines("fseni", con)
  writeLines(paste(sprintf("%.3f",fseni), collapse = "     "), con)
  writeLines("fsenl", con)
  writeLines(paste(sprintf("%.3f",fsenl), collapse = "     "), con)
  writeLines("fsens", con)
  writeLines(paste(sprintf("%.3f",fsens), collapse = "     "), con)
  writeLines("fsenu", con)
  writeLines(paste(sprintf("%.3f",fsenu), collapse = "     "), con)
  writeLines("fvapa", con)
  writeLines(paste(sprintf("%.3f",fvapa), collapse = "     "), con)
  writeLines("fvapg", con)
  writeLines(paste(sprintf("%.3f",fvapg), collapse = "     "), con)
  writeLines("fvapi", con)
  writeLines(paste(sprintf("%.3f",fvapi), collapse = "     "), con)
  writeLines("fvaplt", con)
  writeLines(paste(sprintf("%.3f",fvaplt), collapse = "     "), con)
  writeLines("fvaplw", con)
  writeLines(paste(sprintf("%.3f",fvaplw), collapse = "     "), con)
  writeLines("fvaps", con)
  writeLines(paste(sprintf("%.3f",fvaps), collapse = "     "), con)
  writeLines("fvaput", con)
  writeLines(paste(sprintf("%.3f",fvaput), collapse = "     "), con)
  writeLines("fvapuw", con)
  writeLines(paste(sprintf("%.3f",fvapuw), collapse = "     "), con)
  writeLines("soli", con)
  writeLines(paste(sprintf("%.3f",soli), collapse = "     "), con)
  writeLines("solg", con)
  writeLines(paste(sprintf("%.3f",solg), collapse = "     "), con)
  writeLines("soll", con)
  writeLines(paste(sprintf("%.3f",soll), collapse = "     "), con)
  writeLines("sols", con)
  writeLines(paste(sprintf("%.3f",sols), collapse = "     "), con)
  writeLines("solu", con)
  writeLines(paste(sprintf("%.3f",solu), collapse = "     "), con)
  writeLines("raing", con)
  writeLines(paste(sprintf("%.3f",raing), collapse = "     "), con)
  writeLines("rainl", con)
  writeLines(paste(sprintf("%.3f",rainl), collapse = "     "), con)
  writeLines("rainu", con)
  writeLines(paste(sprintf("%.3f",rainu), collapse = "     "), con)
  writeLines("snowg", con)
  writeLines(paste(sprintf("%.3f",snowg), collapse = "     "), con)
  writeLines("snowl", con)
  writeLines(paste(sprintf("%.3f",snowl), collapse = "     "), con)
  writeLines("snowu", con)
  writeLines(paste(sprintf("%.3f",snowu), collapse = "     "), con)
  writeLines("traing", con)
  writeLines(paste(sprintf("%.3f",traing), collapse = "     "), con)
  writeLines("trainl", con)
  writeLines(paste(sprintf("%.3f",trainl), collapse = "     "), con)
  writeLines("trainu", con)
  writeLines(paste(sprintf("%.3f",trainu), collapse = "     "), con)
  writeLines("tsnowg", con)
  writeLines(paste(sprintf("%.3f",tsnowg), collapse = "     "), con)
  writeLines("tsnowl", con)
  writeLines(paste(sprintf("%.3f",tsnowl), collapse = "     "), con)
  writeLines("tsnowu", con)
  writeLines(paste(sprintf("%.3f",tsnowu), collapse = "     "), con)
  writeLines("nsol", con)
  writeLines(paste(sprintf("%.3f",nsol), collapse = "     "), con)
  writeLines("abupd", con)
  writeLines(paste(sprintf("%.3f",abupd), collapse = "     "), con)
  writeLines("abupi", con)
  writeLines(paste(sprintf("%.3f",abupi), collapse = "     "), con)
  writeLines("ablod", con)
  writeLines(paste(sprintf("%.3f",ablod), collapse = "     "), con)
  writeLines("abloi", con)
  writeLines(paste(sprintf("%.3f",abloi), collapse = "     "), con)
  writeLines("albsnd", con)
  writeLines(paste(sprintf("%.3f",albsnd), collapse = "     "), con)
  writeLines("albsni", con)
  writeLines(paste(sprintf("%.3f",albsni), collapse = "     "), con)
  writeLines("albsod", con)
  writeLines(paste(sprintf("%.3f",albsod), collapse = "     "), con)
  writeLines("albsoi", con)
  writeLines(paste(sprintf("%.3f",albsoi), collapse = "     "), con)
  writeLines("dummy", con)
  writeLines(paste(sprintf("%.3f",dummy), collapse = "     "), con)
  writeLines("flodd", con)
  writeLines(paste(sprintf("%.3f",flodd), collapse = "     "), con)
  writeLines("flodi", con)
  writeLines(paste(sprintf("%.3f",flodi), collapse = "     "), con)
  writeLines("floii", con)
  writeLines(paste(sprintf("%.3f",floii), collapse = "     "), con)
  writeLines("fupdd", con)
  writeLines(paste(sprintf("%.3f",fupdd), collapse = "     "), con)
  writeLines("fupdi", con)
  writeLines(paste(sprintf("%.3f",fupdi), collapse = "     "), con)
  writeLines("fupii", con)
  writeLines(paste(sprintf("%.3f",fupii), collapse = "     "), con)
  writeLines("relod", con)
  writeLines(paste(sprintf("%.3f",relod), collapse = "     "), con)
  writeLines("reloi", con)
  writeLines(paste(sprintf("%.3f",reloi), collapse = "     "), con)
  writeLines("reupd", con)
  writeLines(paste(sprintf("%.3f",reupd), collapse = "     "), con)
  writeLines("reupi", con)
  writeLines(paste(sprintf("%.3f",reupi), collapse = "     "), con)
  writeLines("sol2d", con)
  writeLines(paste(sprintf("%.3f",sol2d), collapse = "     "), con)
  writeLines("sol2i", con)
  writeLines(paste(sprintf("%.3f",sol2i), collapse = "     "), con)
  writeLines("sol3d", con)
  writeLines(paste(sprintf("%.3f",sol3d), collapse = "     "), con)
  writeLines("sol3i", con)
  writeLines(paste(sprintf("%.3f",sol3i), collapse = "     "), con)
  writeLines("indsol", con)
  writeLines(paste(sprintf("%.3f",indsol), collapse = "     "), con)
  writeLines("aloga", con)
  writeLines(paste(sprintf("%.3f",aloga), collapse = "     "), con)
  writeLines("alogav", con)
  writeLines(paste(sprintf("%.3f",alogav), collapse = "     "), con)
  writeLines("alogg", con)
  writeLines(paste(sprintf("%.3f",alogg), collapse = "     "), con)
  writeLines("alogi", con)
  writeLines(paste(sprintf("%.3f",alogi), collapse = "     "), con)
  writeLines("alogl", con)
  writeLines(paste(sprintf("%.3f",alogl), collapse = "     "), con)
  writeLines("alogu", con)
  writeLines(paste(sprintf("%.3f",alogu), collapse = "     "), con)
  writeLines("alog1", con)
  writeLines(paste(sprintf("%.3f",alog1), collapse = "     "), con)
  writeLines("alog2", con)
  writeLines(paste(sprintf("%.3f",alog2), collapse = "     "), con)
  writeLines("alog3", con)
  writeLines(paste(sprintf("%.3f",alog3), collapse = "     "), con)
  writeLines("alog4", con)
  writeLines(paste(sprintf("%.3f",alog4), collapse = "     "), con)
  writeLines("bdl", con)
  writeLines(paste(sprintf("%.3f",bdl), collapse = "     "), con)
  writeLines("bdu", con)
  writeLines(paste(sprintf("%.3f",bdu), collapse = "     "), con)
  writeLines("cl", con)
  writeLines(paste(sprintf("%.3f",cl), collapse = "     "), con)
  writeLines("cp", con)
  writeLines(paste(sprintf("%.3f",cp), collapse = "     "), con)
  writeLines("cu", con)
  writeLines(paste(sprintf("%.3f",cu), collapse = "     "), con)
  writeLines("dil", con)
  writeLines(paste(sprintf("%.3f",dil), collapse = "     "), con)
  writeLines("displ", con)
  writeLines(paste(sprintf("%.3f",displ), collapse = "     "), con)
  writeLines("dispu", con)
  writeLines(paste(sprintf("%.3f",dispu), collapse = "     "), con)
  writeLines("diu", con)
  writeLines(paste(sprintf("%.3f",diu), collapse = "     "), con)
  writeLines("expl", con)
  writeLines(paste(sprintf("%.3f",expl), collapse = "     "), con)
  writeLines("expu", con)
  writeLines(paste(sprintf("%.3f",expu), collapse = "     "), con)
  writeLines("exphl", con)
  writeLines(paste(sprintf("%.3f",exphl), collapse = "     "), con)
  writeLines("exphu", con)
  writeLines(paste(sprintf("%.3f",exphu), collapse = "     "), con)
  writeLines("pfluxl", con)
  writeLines(paste(sprintf("%.3f",pfluxl), collapse = "     "), con)
  writeLines("pfluxs", con)
  writeLines(paste(sprintf("%.3f",pfluxs), collapse = "     "), con)
  writeLines("pfluxu", con)
  writeLines(paste(sprintf("%.3f",pfluxu), collapse = "     "), con)
  writeLines("rhoa", con)
  writeLines(paste(sprintf("%.3f",rhoa), collapse = "     "), con)
  writeLines("richl", con)
  writeLines(paste(sprintf("%.3f",richl), collapse = "     "), con)
  writeLines("richu", con)
  writeLines(paste(sprintf("%.3f",richu), collapse = "     "), con)
  writeLines("sg", con)
  writeLines(paste(sprintf("%.3f",sg), collapse = "     "), con)
  writeLines("si", con)
  writeLines(paste(sprintf("%.3f",si), collapse = "     "), con)
  writeLines("strahl", con)
  writeLines(paste(sprintf("%.3f",strahl), collapse = "     "), con)
  writeLines("strahu", con)
  writeLines(paste(sprintf("%.3f",strahu), collapse = "     "), con)
  writeLines("straml", con)
  writeLines(paste(sprintf("%.3f",straml), collapse = "     "), con)
  writeLines("stramu", con)
  writeLines(paste(sprintf("%.3f",stramu), collapse = "     "), con)
  writeLines("u1", con)
  writeLines(paste(sprintf("%.3f",u1), collapse = "     "), con)
  writeLines("u12", con)
  writeLines(paste(sprintf("%.3f",u12), collapse = "     "), con)
  writeLines("u2", con)
  writeLines(paste(sprintf("%.3f",u2), collapse = "     "), con)
  writeLines("u3", con)
  writeLines(paste(sprintf("%.3f",u3), collapse = "     "), con)
  writeLines("u34", con)
  writeLines(paste(sprintf("%.3f",u34), collapse = "     "), con)
  writeLines("u4", con)
  writeLines(paste(sprintf("%.3f",u4), collapse = "     "), con)
  writeLines("za", con)
  writeLines(paste(sprintf("%.3f",za), collapse = "     "), con)
  writeLines("z1", con)
  writeLines(paste(sprintf("%.3f",z1), collapse = "     "), con)
  writeLines("z12", con)
  writeLines(paste(sprintf("%.3f",z12), collapse = "     "), con)
  writeLines("z2", con)
  writeLines(paste(sprintf("%.3f",z2), collapse = "     "), con)
  writeLines("z3", con)
  writeLines(paste(sprintf("%.3f",z3), collapse = "     "), con)
  writeLines("z34", con)
  writeLines(paste(sprintf("%.3f",z34), collapse = "     "), con)
  writeLines("z4", con)
  writeLines(paste(sprintf("%.3f",z4), collapse = "     "), con)
  writeLines("tfac", con)
  writeLines(paste(sprintf("%.3f",tfac), collapse = "     "), con)
  writeLines("fwetl", con)
  writeLines(paste(sprintf("%.3f",fwetl), collapse = "     "), con)
  writeLines("fwets", con)
  writeLines(paste(sprintf("%.3f",fwets), collapse = "     "), con)
  writeLines("fwetu", con)
  writeLines(paste(sprintf("%.3f",fwetu), collapse = "     "), con)
  writeLines("fwetlx", con)
  writeLines(paste(sprintf("%.3f",fwetlx), collapse = "     "), con)
  writeLines("fwetsx", con)
  writeLines(paste(sprintf("%.3f",fwetsx), collapse = "     "), con)
  writeLines("fwetux", con)
  writeLines(paste(sprintf("%.3f",fwetux), collapse = "     "), con)
  writeLines("rliql", con)
  writeLines(paste(sprintf("%.3f",rliql), collapse = "     "), con)
  writeLines("rliqs", con)
  writeLines(paste(sprintf("%.3f",rliqs), collapse = "     "), con)
  writeLines("rliqu", con)
  writeLines(paste(sprintf("%.3f",rliqu), collapse = "     "), con)
  writeLines("coszen", con)
  writeLines(paste(sprintf("%.3f",coszen), collapse = "     "), con)
  writeLines("fira", con)
  writeLines(paste(sprintf("%.3f",fira), collapse = "     "), con)
  writeLines("solad", con)
  writeLines(paste(sprintf("%.3f",solad), collapse = "     "), con)
  writeLines("solai", con)
  writeLines(paste(sprintf("%.3f",solai), collapse = "     "), con)
  writeLines("asurd", con)
  writeLines(paste(sprintf("%.3f",asurd), collapse = "     "), con)
  writeLines("asuri", con)
  writeLines(paste(sprintf("%.3f",asuri), collapse = "     "), con)
  writeLines("radd", con)
  writeLines(paste(sprintf("%.3f",radd), collapse = "     "), con)
  writeLines("solsoi", con)
  writeLines(paste(sprintf("%.3f",solsoi), collapse = "     "), con)
  writeLines("ua", con)
  writeLines(paste(sprintf("%.3f",ua), collapse = "     "), con)
  writeLines("ta", con)
  writeLines(paste(sprintf("%.3f",ta), collapse = "     "), con)
  writeLines("qa", con)
  writeLines(paste(sprintf("%.3f",qa), collapse = "     "), con)
  writeLines("raina", con)
  writeLines(paste(sprintf("%.3f",raina), collapse = "     "), con)
  writeLines("rh", con)
  writeLines(paste(sprintf("%.3f",rh), collapse = "     "), con)
  writeLines("snowa", con)
  writeLines(paste(sprintf("%.3f",snowa), collapse = "     "), con)
  writeLines("psurf", con)
  writeLines(paste(sprintf("%.3f",psurf), collapse = "     "), con)
  writeLines("cloud", con)
  writeLines(paste(sprintf("%.3f",cloud), collapse = "     "), con)
  writeLines("td", con)
  writeLines(paste(sprintf("%.3f",td), collapse = "     "), con)
  writeLines("tmax", con)
  writeLines(paste(sprintf("%.3f",tmax), collapse = "     "), con)
  writeLines("tmin", con)
  writeLines(paste(sprintf("%.3f",tmin), collapse = "     "), con)
  writeLines("qd", con)
  writeLines(paste(sprintf("%.3f",qd), collapse = "     "), con)
  writeLines("ud", con)
  writeLines(paste(sprintf("%.3f",ud), collapse = "     "), con)
  writeLines("precip", con)
  writeLines(paste(sprintf("%.3f",precip), collapse = "     "), con)
  writeLines("precipday", con)
  writeLines(paste(sprintf("%.3f",precipday), collapse = "     "), con)
  writeLines("precipdaysum", con)
  writeLines(paste(sprintf("%.3f",precipdaysum), collapse = "     "), con)
  writeLines("xstore", con)
  writeLines(paste(sprintf("%.3f",xstore), collapse = "     "), con)
  writeLines("iwet", con)
  writeLines(paste(sprintf("%.3f",iwet), collapse = "     "), con)
  writeLines("iwetday", con)
  writeLines(paste(sprintf("%.3f",iwetday), collapse = "     "), con)
  writeLines("iwetdaysum", con)
  writeLines(paste(sprintf("%.3f",iwetdaysum), collapse = "     "), con)
  writeLines("co2conc", con)
  writeLines(paste(sprintf("%.3f",co2conc), collapse = "     "), con)
  writeLines("o2conc", con)
  writeLines(paste(sprintf("%.3f",o2conc), collapse = "     "), con)
  writeLines("t_sec", con)
  writeLines(paste(sprintf("%.3f",t_sec), collapse = "     "), con)
  writeLines("t_startp", con)
  writeLines(paste(sprintf("%.3f",t_startp), collapse = "     "), con)
  writeLines("xintopo", con)
  writeLines(paste(sprintf("%.3f",xintopo), collapse = "     "), con)
  writeLines("xinveg", con)
  writeLines(paste(sprintf("%.3f",xinveg), collapse = "     "), con)
  # writeLines("deltat", con)
  # writeLines(paste(sprintf("%.3f",deltat), collapse = "     "), con)
  writeLines("ireccru", con)
  writeLines(paste(sprintf("%.3f",ireccru), collapse = "     "), con)
  writeLines("ireccdc", con)
  writeLines(paste(sprintf("%.3f",ireccdc), collapse = "     "), con)
  # writeLines("xint", con)
  # writeLines(paste(sprintf("%.3f",xint), collapse = "     "), con)
  # writeLines("xinq", con)
  # writeLines(paste(sprintf("%.3f",xinq), collapse = "     "), con)
  # writeLines("xinprec", con)
  # writeLines(paste(sprintf("%.3f",xinprec), collapse = "     "), con)
  # writeLines("xinwind", con)
  # writeLines(paste(sprintf("%.3f",xinwind), collapse = "     "), con)
  # writeLines("xincld", con)
  # writeLines(paste(sprintf("%.3f",xincld), collapse = "     "), con)
  # writeLines("xinwet", con)
  # writeLines(paste(sprintf("%.3f",xinwet), collapse = "     "), con)
  # writeLines("xintrng", con)
  # writeLines(paste(sprintf("%.3f",xintrng), collapse = "     "), con)
  # writeLines("xintmxc", con)
  # writeLines(paste(sprintf("%.3f",xintmxc), collapse = "     "), con)
  # writeLines("xintmmc", con)
  # writeLines(paste(sprintf("%.3f",xintmmc), collapse = "     "), con)
  writeLines("clmt", con)
  writeLines(paste(sprintf("%.3f",clmt), collapse = "     "), con)
  writeLines("clmq", con)
  writeLines(paste(sprintf("%.3f",clmq), collapse = "     "), con)
  writeLines("clmprec", con)
  writeLines(paste(sprintf("%.3f",clmprec), collapse = "     "), con)
  writeLines("clmw", con)
  writeLines(paste(sprintf("%.3f",clmw), collapse = "     "), con)
  writeLines("clmwet", con)
  writeLines(paste(sprintf("%.3f",clmwet), collapse = "     "), con)
  writeLines("clmcld", con)
  writeLines(paste(sprintf("%.3f",clmcld), collapse = "     "), con)
  writeLines("clmtrng", con)
  writeLines(paste(sprintf("%.3f",clmtrng), collapse = "     "), con)
  # writeLines("xintd", con)
  # writeLines(paste(sprintf("%.3f",xintd), collapse = "     "), con)
  # writeLines("xinqd", con)
  # writeLines(paste(sprintf("%.3f",xinqd), collapse = "     "), con)
  # writeLines("xinprecd", con)
  # writeLines(paste(sprintf("%.3f",xinprecd), collapse = "     "), con)
  # writeLines("xinwindd", con)
  # writeLines(paste(sprintf("%.3f",xinwindd), collapse = "     "), con)
  # writeLines("xincldd", con)
  # writeLines(paste(sprintf("%.3f",xincldd), collapse = "     "), con)
  # writeLines("xintrngd", con)
  # writeLines(paste(sprintf("%.3f",xintrngd), collapse = "     "), con)
  # writeLines("xintmax", con)
  # writeLines(paste(sprintf("%.3f",xintmax), collapse = "     "), con)
  # writeLines("xintmin", con)
  # writeLines(paste(sprintf("%.3f",xintmin), collapse = "     "), con)
  # writeLines("xinavepdate", con)
  # writeLines(paste(sprintf("%.3f",xinavepdate), collapse = "     "), con)
  # writeLines("xinavehybrid", con)
  # writeLines(paste(sprintf("%.3f",xinavehybrid), collapse = "     "), con)
  writeLines("cdcinprecd", con)
  writeLines(paste(sprintf("%.3f",cdcinprecd), collapse = "     "), con)
  # writeLines("stintd", con)
  # writeLines(paste(sprintf("%.3f",stintd), collapse = "     "), con)
  # writeLines("stinqd", con)
  # writeLines(paste(sprintf("%.3f",stinqd), collapse = "     "), con)
  # writeLines("stinprecd", con)
  # writeLines(paste(sprintf("%.3f",stinprecd), collapse = "     "), con)
  # writeLines("stinwindd", con)
  # writeLines(paste(sprintf("%.3f",stinwindd), collapse = "     "), con)
  # writeLines("stincldd", con)
  # writeLines(paste(sprintf("%.3f",stincldd), collapse = "     "), con)
  # writeLines("stintmax", con)
  # writeLines(paste(sprintf("%.3f",stintmax), collapse = "     "), con)
  # writeLines("stintmin", con)
  # writeLines(paste(sprintf("%.3f",stintmin), collapse = "     "), con)
  writeLines("stinrad", con)
  writeLines(paste(sprintf("%.3f",stinrad), collapse = "     "), con)
  writeLines("lig_frac", con)
  writeLines(paste(sprintf("%.3f",lig_frac), collapse = "     "), con)
  writeLines("fbsom", con)
  writeLines(paste(sprintf("%.3f",fbsom), collapse = "     "), con)
  writeLines("effac", con)
  writeLines(paste(sprintf("%.3f",effac), collapse = "     "), con)
  writeLines("cnr", con)
  writeLines(paste(sprintf("%.3f",cnr), collapse = "     "), con)
  writeLines("fmxcpool", con)
  writeLines(paste(sprintf("%.3f",fmxcpool), collapse = "     "), con)
  writeLines("rconst", con)
  writeLines(paste(sprintf("%.3f",rconst), collapse = "     "), con)
  writeLines("h20", con)
  writeLines(paste(sprintf("%.3f",h20), collapse = "     "), con)
  writeLines("klm", con)
  writeLines(paste(sprintf("%.3f",klm), collapse = "     "), con)
  writeLines("kls", con)
  writeLines(paste(sprintf("%.3f",kls), collapse = "     "), con)
  writeLines("kll", con)
  writeLines(paste(sprintf("%.3f",kll), collapse = "     "), con)
  writeLines("krm", con)
  writeLines(paste(sprintf("%.3f",krm), collapse = "     "), con)
  writeLines("krs", con)
  writeLines(paste(sprintf("%.3f",krs), collapse = "     "), con)
  writeLines("krl", con)
  writeLines(paste(sprintf("%.3f",krl), collapse = "     "), con)
  writeLines("kwm", con)
  writeLines(paste(sprintf("%.3f",kwm), collapse = "     "), con)
  writeLines("kws", con)
  writeLines(paste(sprintf("%.3f",kws), collapse = "     "), con)
  writeLines("kwl", con)
  writeLines(paste(sprintf("%.3f",kwl), collapse = "     "), con)
  writeLines("kbn", con)
  writeLines(paste(sprintf("%.3f",kbn), collapse = "     "), con)
  writeLines("kbp", con)
  writeLines(paste(sprintf("%.3f",kbp), collapse = "     "), con)
  writeLines("knb", con)
  writeLines(paste(sprintf("%.3f",knb), collapse = "     "), con)
  writeLines("kns", con)
  writeLines(paste(sprintf("%.3f",kns), collapse = "     "), con)
  writeLines("kpb", con)
  writeLines(paste(sprintf("%.3f",kpb), collapse = "     "), con)
  writeLines("kps", con)
  writeLines(paste(sprintf("%.3f",kps), collapse = "     "), con)
  writeLines("ksb", con)
  writeLines(paste(sprintf("%.3f",ksb), collapse = "     "), con)
  writeLines("ylm", con)
  writeLines(paste(sprintf("%.3f",ylm), collapse = "     "), con)
  writeLines("yls", con)
  writeLines(paste(sprintf("%.3f",yls), collapse = "     "), con)
  writeLines("yll", con)
  writeLines(paste(sprintf("%.3f",yll), collapse = "     "), con)
  writeLines("yrm", con)
  writeLines(paste(sprintf("%.3f",yrm), collapse = "     "), con)
  writeLines("yrs", con)
  writeLines(paste(sprintf("%.3f",yrs), collapse = "     "), con)
  writeLines("yrl", con)
  writeLines(paste(sprintf("%.3f",yrl), collapse = "     "), con)
  writeLines("ywm", con)
  writeLines(paste(sprintf("%.3f",ywm), collapse = "     "), con)
  writeLines("yws", con)
  writeLines(paste(sprintf("%.3f",yws), collapse = "     "), con)
  writeLines("ywl", con)
  writeLines(paste(sprintf("%.3f",ywl), collapse = "     "), con)
  writeLines("ybn", con)
  writeLines(paste(sprintf("%.3f",ybn), collapse = "     "), con)
  writeLines("ybp", con)
  writeLines(paste(sprintf("%.3f",ybp), collapse = "     "), con)
  writeLines("ynb", con)
  writeLines(paste(sprintf("%.3f",ynb), collapse = "     "), con)
  writeLines("yns", con)
  writeLines(paste(sprintf("%.3f",yns), collapse = "     "), con)
  writeLines("ypb", con)
  writeLines(paste(sprintf("%.3f",ypb), collapse = "     "), con)
  writeLines("yps", con)
  writeLines(paste(sprintf("%.3f",yps), collapse = "     "), con)
  writeLines("ysb", con)
  writeLines(paste(sprintf("%.3f",ysb), collapse = "     "), con)
  writeLines("isoybean", con)
  writeLines(paste(sprintf("%.3f",isoybean), collapse = "     "), con)
  writeLines("imaize", con)
  writeLines(paste(sprintf("%.3f",imaize), collapse = "     "), con)
  writeLines("isgc", con)
  writeLines(paste(sprintf("%.3f",isgc), collapse = "     "), con)
  writeLines("iwheat", con)
  writeLines(paste(sprintf("%.3f",iwheat), collapse = "     "), con)
  writeLines("gdddy", con)
  writeLines(paste(sprintf("%.3f",gdddy), collapse = "     "), con)
  writeLines("ipast", con)
  writeLines(paste(sprintf("%.3f",ipast), collapse = "     "), con)
  writeLines("ik", con)
  writeLines(paste(sprintf("%.3f",ik), collapse = "     "), con)
  writeLines("qgalho", con)
  writeLines(paste(sprintf("%.3f",qgalho), collapse = "     "), con)
  writeLines("istyear", con)
  writeLines(paste(sprintf("%.3f",istyear), collapse = "     "), con)
  writeLines("istend", con)
  writeLines(paste(sprintf("%.3f",istend), collapse = "     "), con)
  # writeLines("cdcyear", con)
  # writeLines(paste(sprintf("%.3f",cdcyear), collapse = "     "), con)
  writeLines("irotation", con)
  writeLines(paste(sprintf("%.3f",irotation), collapse = "     "), con)
  writeLines("isoilay", con)
  writeLines(paste(sprintf("%.3f",isoilay), collapse = "     "), con)
  writeLines("cdays", con)
  writeLines(paste(sprintf("%.3f",cdays), collapse = "     "), con)
  writeLines("pstart", con)
  writeLines(paste(sprintf("%.3f",pstart), collapse = "     "), con)
  writeLines("nratoon", con)
  writeLines(paste(sprintf("%.3f",nratoon), collapse = "     "), con)
  writeLines("ncyears", con)
  writeLines(paste(sprintf("%.3f",ncyears), collapse = "     "), con)
  writeLines("cropy", con)
  writeLines(paste(sprintf("%.3f",cropy), collapse = "     "), con)
  writeLines("overveg", con)
  writeLines(paste(sprintf("%.3f",overveg), collapse = "     "), con)
  writeLines("nplant", con)
  writeLines(paste(sprintf("%.3f",nplant), collapse = "     "), con)
  writeLines("iniday", con)
  writeLines(paste(sprintf("%.3f",iniday), collapse = "     "), con)
  writeLines("endday", con)
  writeLines(paste(sprintf("%.3f",endday), collapse = "     "), con)
  # writeLines("ztopmxsoy", con)
  # writeLines(paste(sprintf("%.3f",ztopmxsoy), collapse = "     "), con)
  # writeLines("ztopmxwht", con)
  # writeLines(paste(sprintf("%.3f",ztopmxwht), collapse = "     "), con)
  # writeLines("ztopmxmze", con)
  # writeLines(paste(sprintf("%.3f",ztopmxmze), collapse = "     "), con)
  # writeLines("ztopmxsgc", con)
  # writeLines(paste(sprintf("%.3f",ztopmxsgc), collapse = "     "), con)
  writeLines("laidcs", con)
  writeLines(paste(sprintf("%.3f",laidcs), collapse = "     "), con)
  writeLines("alphac", con)
  writeLines(paste(sprintf("%.3f",alphac), collapse = "     "), con)
  writeLines("gnmin", con)
  writeLines(paste(sprintf("%.3f",gnmin), collapse = "     "), con)
  writeLines("smax", con)
  writeLines(paste(sprintf("%.3f",smax), collapse = "     "), con)
  writeLines("availn", con)
  writeLines(paste(sprintf("%.3f",availn), collapse = "     "), con)
  writeLines("cnmax", con)
  writeLines(paste(sprintf("%.3f",cnmax), collapse = "     "), con)
  writeLines("mxtsuc", con)
  writeLines(paste(sprintf("%.3f",mxtsuc), collapse = "     "), con)
  writeLines("consdays", con)
  writeLines(paste(sprintf("%.3f",consdays), collapse = "     "), con)
  writeLines("maxcons", con)
  writeLines(paste(sprintf("%.3f",maxcons), collapse = "     "), con)
  writeLines("gsdays", con)
  writeLines(paste(sprintf("%.3f",gsdays), collapse = "     "), con)
  writeLines("rootd", con)
  writeLines(paste(sprintf("%.3f",rootd), collapse = "     "), con)
  writeLines("af1", con)
  writeLines(paste(sprintf("%.3f",af1), collapse = "     "), con)
  writeLines("af2", con)
  writeLines(paste(sprintf("%.3f",af2), collapse = "     "), con)
  writeLines("af3", con)
  writeLines(paste(sprintf("%.3f",af3), collapse = "     "), con)
  writeLines("af4", con)
  writeLines(paste(sprintf("%.3f",af4), collapse = "     "), con)
  writeLines("af5", con)
  writeLines(paste(sprintf("%.3f",af5), collapse = "     "), con)
  writeLines("af6", con)
  writeLines(paste(sprintf("%.3f",af6), collapse = "     "), con)
  writeLines("sf1", con)
  writeLines(paste(sprintf("%.3f",sf1), collapse = "     "), con)
  writeLines("ipf1", con)
  writeLines(paste(sprintf("%.3f",ipf1), collapse = "     "), con)
  writeLines("sf3", con)
  writeLines(paste(sprintf("%.3f",sf3), collapse = "     "), con)
  writeLines("ipf3", con)
  writeLines(paste(sprintf("%.3f",ipf3), collapse = "     "), con)
  writeLines("ldf", con)
  writeLines(paste(sprintf("%.3f",ldf), collapse = "     "), con)
  writeLines("tmld", con)
  writeLines(paste(sprintf("%.3f",tmld), collapse = "     "), con)
  writeLines("ecf2", con)
  writeLines(paste(sprintf("%.3f",ecf2), collapse = "     "), con)
  writeLines("ipf2", con)
  writeLines(paste(sprintf("%.3f",ipf2), collapse = "     "), con)
  writeLines("ecf4", con)
  writeLines(paste(sprintf("%.3f",ecf4), collapse = "     "), con)
  writeLines("ipf4", con)
  writeLines(paste(sprintf("%.3f",ipf4), collapse = "     "), con)
  writeLines("ecf5", con)
  writeLines(paste(sprintf("%.3f",ecf5), collapse = "     "), con)
  writeLines("tf5", con)
  writeLines(paste(sprintf("%.3f",tf5), collapse = "     "), con)
  writeLines("wf5", con)
  writeLines(paste(sprintf("%.3f",wf5), collapse = "     "), con)
  writeLines("ecf6", con)
  writeLines(paste(sprintf("%.3f",ecf6), collapse = "     "), con)
  writeLines("ipf6", con)
  writeLines(paste(sprintf("%.3f",ipf6), collapse = "     "), con)
  writeLines("ecf7", con)
  writeLines(paste(sprintf("%.3f",ecf7), collapse = "     "), con)
  writeLines("laidc", con)
  writeLines(paste(sprintf("%.3f",laidc), collapse = "     "), con)
  writeLines("firecane", con)
  writeLines(paste(sprintf("%.3f",firecane), collapse = "     "), con)
  writeLines("xirrig", con)
  writeLines(paste(sprintf("%.3f",xirrig), collapse = "     "), con)
  writeLines("xirriga", con)
  writeLines(paste(sprintf("%.3f",xirriga), collapse = "     "), con)
  writeLines("totirrig", con)
  writeLines(paste(sprintf("%.3f",totirrig), collapse = "     "), con)
  # writeLines("cropsum", con)
  # writeLines(paste(sprintf("%.3f",cropsum), collapse = "     "), con)
  writeLines("df", con)
  writeLines(paste(sprintf("%.3f",df), collapse = "     "), con)
  writeLines("vf", con)
  writeLines(paste(sprintf("%.3f",vf), collapse = "     "), con)
  writeLines("pmask", con)
  writeLines(paste(sprintf("%.3f",pmask), collapse = "     "), con)
  writeLines("cumvd", con)
  writeLines(paste(sprintf("%.3f",cumvd), collapse = "     "), con)
  writeLines("hdidx", con)
  writeLines(paste(sprintf("%.3f",hdidx), collapse = "     "), con)
  # writeLines("gddfzcorn", con)
  # writeLines(paste(sprintf("%.3f",gddfzcorn), collapse = "     "), con)
  # writeLines("gddfzsoy", con)
  # writeLines(paste(sprintf("%.3f",gddfzsoy), collapse = "     "), con)
  # writeLines("gddfzwht", con)
  # writeLines(paste(sprintf("%.3f",gddfzwht), collapse = "     "), con)
  # writeLines("gddfzsgc", con)
  # writeLines(paste(sprintf("%.3f",gddfzsgc), collapse = "     "), con)
  writeLines("conspdate", con)
  writeLines(paste(sprintf("%.3f",conspdate), collapse = "     "), con)
  writeLines("conshybrid", con)
  writeLines(paste(sprintf("%.3f",conshybrid), collapse = "     "), con)
  writeLines("ptemp", con)
  writeLines(paste(sprintf("%.3f",ptemp), collapse = "     "), con)
  writeLines("pmintemp", con)
  writeLines(paste(sprintf("%.3f",pmintemp), collapse = "     "), con)
  writeLines("pmmin", con)
  writeLines(paste(sprintf("%.3f",pmmin), collapse = "     "), con)
  writeLines("pdmin", con)
  writeLines(paste(sprintf("%.3f",pdmin), collapse = "     "), con)
  writeLines("pcm", con)
  writeLines(paste(sprintf("%.3f",pcm), collapse = "     "), con)
  writeLines("pcd", con)
  writeLines(paste(sprintf("%.3f",pcd), collapse = "     "), con)
  writeLines("gddsgcp", con)
  writeLines(paste(sprintf("%.3f",gddsgcp), collapse = "     "), con)
  writeLines("idop", con)
  writeLines(paste(sprintf("%.3f",idop), collapse = "     "), con)
  writeLines("iavepdate", con)
  writeLines(paste(sprintf("%.3f",iavepdate), collapse = "     "), con)
  writeLines("harvdate", con)
  writeLines(paste(sprintf("%.3f",harvdate), collapse = "     "), con)
  writeLines("cntops", con)
  writeLines(paste(sprintf("%.3f",cntops), collapse = "     "), con)
  writeLines("cnroot", con)
  writeLines(paste(sprintf("%.3f",cnroot), collapse = "     "), con)
  writeLines("croplive", con)
  writeLines(paste(sprintf("%.3f",croplive), collapse = "     "), con)
  writeLines("grnfraccrop", con)
  writeLines(paste(sprintf("%.3f",grnfraccrop), collapse = "     "), con)
  writeLines("gddplant", con)
  writeLines(paste(sprintf("%.3f",gddplant), collapse = "     "), con)
  writeLines("gddtsoi", con)
  writeLines(paste(sprintf("%.3f",gddtsoi), collapse = "     "), con)
  writeLines("gddmaturity", con)
  writeLines(paste(sprintf("%.3f",gddmaturity), collapse = "     "), con)
  writeLines("thrlai", con)
  writeLines(paste(sprintf("%.3f",thrlai), collapse = "     "), con)
  writeLines("peaklai", con)
  writeLines(paste(sprintf("%.3f",peaklai), collapse = "     "), con)
  writeLines("hui", con)
  writeLines(paste(sprintf("%.3f",hui), collapse = "     "), con)
  writeLines("phuf", con)
  writeLines(paste(sprintf("%.3f",phuf), collapse = "     "), con)
  writeLines("tlai", con)
  writeLines(paste(sprintf("%.3f",tlai), collapse = "     "), con)
  writeLines("templai", con)
  writeLines(paste(sprintf("%.3f",templai), collapse = "     "), con)
  writeLines("harvidx", con)
  writeLines(paste(sprintf("%.3f",harvidx), collapse = "     "), con)
  # writeLines("gddpl15", con)
  # writeLines(paste(sprintf("%.3f",gddpl15), collapse = "     "), con)
  writeLines("gddemerg", con)
  writeLines(paste(sprintf("%.3f",gddemerg), collapse = "     "), con)
  writeLines("fnleaf", con)
  writeLines(paste(sprintf("%.3f",fnleaf), collapse = "     "), con)
  writeLines("fnstem", con)
  writeLines(paste(sprintf("%.3f",fnstem), collapse = "     "), con)
  writeLines("fnroot", con)
  writeLines(paste(sprintf("%.3f",fnroot), collapse = "     "), con)
  writeLines("fngrain", con)
  writeLines(paste(sprintf("%.3f",fngrain), collapse = "     "), con)
  writeLines("fnplant", con)
  writeLines(paste(sprintf("%.3f",fnplant), collapse = "     "), con)
  writeLines("tnplant", con)
  writeLines(paste(sprintf("%.3f",tnplant), collapse = "     "), con)
  writeLines("grainn", con)
  writeLines(paste(sprintf("%.3f",grainn), collapse = "     "), con)
  writeLines("cumlvs", con)
  writeLines(paste(sprintf("%.3f",cumlvs), collapse = "     "), con)
  writeLines("idpp", con)
  writeLines(paste(sprintf("%.3f",idpp), collapse = "     "), con)
  writeLines("idpe", con)
  writeLines(paste(sprintf("%.3f",idpe), collapse = "     "), con)
  writeLines("dpgf", con)
  writeLines(paste(sprintf("%.3f",dpgf), collapse = "     "), con)
  writeLines("cropyld", con)
  writeLines(paste(sprintf("%.3f",cropyld), collapse = "     "), con)
  writeLines("dmleaf", con)
  writeLines(paste(sprintf("%.3f",dmleaf), collapse = "     "), con)
  writeLines("dmstem", con)
  writeLines(paste(sprintf("%.3f",dmstem), collapse = "     "), con)
  writeLines("dmresidue", con)
  writeLines(paste(sprintf("%.3f",dmresidue), collapse = "     "), con)
  writeLines("dmyield", con)
  writeLines(paste(sprintf("%.3f",dmyield), collapse = "     "), con)
  writeLines("dmcrop", con)
  writeLines(paste(sprintf("%.3f",dmcrop), collapse = "     "), con)
  writeLines("cropn", con)
  writeLines(paste(sprintf("%.3f",cropn), collapse = "     "), con)
  writeLines("cropfixn", con)
  writeLines(paste(sprintf("%.3f",cropfixn), collapse = "     "), con)
  writeLines("nconcl", con)
  writeLines(paste(sprintf("%.3f",nconcl), collapse = "     "), con)
  writeLines("nconcs", con)
  writeLines(paste(sprintf("%.3f",nconcs), collapse = "     "), con)
  writeLines("nconcr", con)
  writeLines(paste(sprintf("%.3f",nconcr), collapse = "     "), con)
  writeLines("nconcg", con)
  writeLines(paste(sprintf("%.3f",nconcg), collapse = "     "), con)
  writeLines("leafout", con)
  writeLines(paste(sprintf("%.3f",leafout), collapse = "     "), con)
  writeLines("cropplant", con)
  writeLines(paste(sprintf("%.3f",cropplant), collapse = "     "), con)
  writeLines("croplaimx", con)
  writeLines(paste(sprintf("%.3f",croplaimx), collapse = "     "), con)
  writeLines("residuen", con)
  writeLines(paste(sprintf("%.3f",residuen), collapse = "     "), con)
  writeLines("dmroot", con)
  writeLines(paste(sprintf("%.3f",dmroot), collapse = "     "), con)
  writeLines("hdate", con)
  writeLines(paste(sprintf("%.3f",hdate), collapse = "     "), con)
  writeLines("pdate", con)
  writeLines(paste(sprintf("%.3f",pdate), collapse = "     "), con)
  writeLines("crmclim", con)
  writeLines(paste(sprintf("%.3f",crmclim), collapse = "     "), con)
  writeLines("crmact", con)
  writeLines(paste(sprintf("%.3f",crmact), collapse = "     "), con)
  writeLines("crmplant", con)
  writeLines(paste(sprintf("%.3f",crmplant), collapse = "     "), con)
  writeLines("ccdays", con)
  writeLines(paste(sprintf("%.3f",ccdays), collapse = "     "), con)
  writeLines("grainday", con)
  writeLines(paste(sprintf("%.3f",grainday), collapse = "     "), con)
  writeLines("fertinput", con)
  writeLines(paste(sprintf("%.3f",fertinput), collapse = "     "), con)
  writeLines("avehybrid", con)
  writeLines(paste(sprintf("%.3f",avehybrid), collapse = "     "), con)
  writeLines("idppout", con)
  writeLines(paste(sprintf("%.3f",idppout), collapse = "     "), con)
  writeLines("aerial", con)
  writeLines(paste(sprintf("%.3f",aerial), collapse = "     "), con)
  writeLines("rm", con)
  writeLines(paste(sprintf("%.3f",rm), collapse = "     "), con)
  writeLines("fertmaize", con)
  writeLines(paste(sprintf("%.3f",fertmaize), collapse = "     "), con)
  writeLines("fertsoy", con)
  writeLines(paste(sprintf("%.3f",fertsoy), collapse = "     "), con)
  writeLines("fertwheat", con)
  writeLines(paste(sprintf("%.3f",fertwheat), collapse = "     "), con)
  writeLines("fertsgc", con)
  writeLines(paste(sprintf("%.3f",fertsgc), collapse = "     "), con)
  writeLines("ndepfact", con)
  writeLines(paste(sprintf("%.3f",ndepfact), collapse = "     "), con)
  # writeLines("xinpdate", con)
  # writeLines(paste(sprintf("%.3f",xinpdate), collapse = "     "), con)
  writeLines("xinhybrid", con)
  writeLines(paste(sprintf("%.3f",xinhybrid), collapse = "     "), con)
  writeLines("arepr", con)
  writeLines(paste(sprintf("%.3f",arepr), collapse = "     "), con)
  writeLines("astem", con)
  writeLines(paste(sprintf("%.3f",astem), collapse = "     "), con)
  writeLines("astemi", con)
  writeLines(paste(sprintf("%.3f",astemi), collapse = "     "), con)
  writeLines("aleafi", con)
  writeLines(paste(sprintf("%.3f",aleafi), collapse = "     "), con)
  writeLines("cfrac", con)
  writeLines(paste(sprintf("%.3f",cfrac), collapse = "     "), con)
  writeLines("baset", con)
  writeLines(paste(sprintf("%.3f",baset), collapse = "     "), con)
  writeLines("mxtmp", con)
  writeLines(paste(sprintf("%.3f",mxtmp), collapse = "     "), con)
  writeLines("tkill", con)
  writeLines(paste(sprintf("%.3f",tkill), collapse = "     "), con)
  writeLines("hybgdd", con)
  writeLines(paste(sprintf("%.3f",hybgdd), collapse = "     "), con)
  writeLines("gddmin", con)
  writeLines(paste(sprintf("%.3f",gddmin), collapse = "     "), con)
  writeLines("lfemerg", con)
  writeLines(paste(sprintf("%.3f",lfemerg), collapse = "     "), con)
  writeLines("grnfill", con)
  writeLines(paste(sprintf("%.3f",grnfill), collapse = "     "), con)
  writeLines("laicons", con)
  writeLines(paste(sprintf("%.3f",laicons), collapse = "     "), con)
  writeLines("allconsl", con)
  writeLines(paste(sprintf("%.3f",allconsl), collapse = "     "), con)
  writeLines("allconss", con)
  writeLines(paste(sprintf("%.3f",allconss), collapse = "     "), con)
  writeLines("laimx", con)
  writeLines(paste(sprintf("%.3f",laimx), collapse = "     "), con)
  writeLines("arooti", con)
  writeLines(paste(sprintf("%.3f",arooti), collapse = "     "), con)
  writeLines("arootf", con)
  writeLines(paste(sprintf("%.3f",arootf), collapse = "     "), con)
  writeLines("aleaff", con)
  writeLines(paste(sprintf("%.3f",aleaff), collapse = "     "), con)
  writeLines("astemf", con)
  writeLines(paste(sprintf("%.3f",astemf), collapse = "     "), con)
  writeLines("declfact", con)
  writeLines(paste(sprintf("%.3f",declfact), collapse = "     "), con)
  writeLines("mxgddgf", con)
  writeLines(paste(sprintf("%.3f",mxgddgf), collapse = "     "), con)
  writeLines("mxdgfi", con)
  writeLines(paste(sprintf("%.3f",mxdgfi), collapse = "     "), con)
  writeLines("mxmat", con)
  writeLines(paste(sprintf("%.3f",mxmat), collapse = "     "), con)
  writeLines("fleafi", con)
  writeLines(paste(sprintf("%.3f",fleafi), collapse = "     "), con)
  writeLines("fleaf", con)
  writeLines(paste(sprintf("%.3f",fleaf), collapse = "     "), con)
  writeLines("cgrain", con)
  writeLines(paste(sprintf("%.3f",cgrain), collapse = "     "), con)
  writeLines("convfact", con)
  writeLines(paste(sprintf("%.3f",convfact), collapse = "     "), con)
  writeLines("maxhi", con)
  writeLines(paste(sprintf("%.3f",maxhi), collapse = "     "), con)
  writeLines("fyield", con)
  writeLines(paste(sprintf("%.3f",fyield), collapse = "     "), con)
  writeLines("fnlfmx", con)
  writeLines(paste(sprintf("%.3f",fnlfmx), collapse = "     "), con)
  writeLines("fngrmx", con)
  writeLines(paste(sprintf("%.3f",fngrmx), collapse = "     "), con)
  writeLines("sratio", con)
  writeLines(paste(sprintf("%.3f",sratio), collapse = "     "), con)
  writeLines("rratio", con)
  writeLines(paste(sprintf("%.3f",rratio), collapse = "     "), con)
  writeLines("fnopt", con)
  writeLines(paste(sprintf("%.3f",fnopt), collapse = "     "), con)
  writeLines("bfact", con)
  writeLines(paste(sprintf("%.3f",bfact), collapse = "     "), con)
  writeLines("grnwht", con)
  writeLines(paste(sprintf("%.3f",grnwht), collapse = "     "), con)
  writeLines("fleafiwht", con)
  writeLines(paste(sprintf("%.3f",fleafiwht), collapse = "     "), con)
  writeLines("fleafwht", con)
  writeLines(paste(sprintf("%.3f",fleafwht), collapse = "     "), con)
  writeLines("mgddgf", con)
  writeLines(paste(sprintf("%.3f",mgddgf), collapse = "     "), con)
  writeLines("mxmatwht", con)
  writeLines(paste(sprintf("%.3f",mxmatwht), collapse = "     "), con)
  writeLines("fnlfmxw", con)
  writeLines(paste(sprintf("%.3f",fnlfmxw), collapse = "     "), con)
  writeLines("fngrmxw", con)
  writeLines(paste(sprintf("%.3f",fngrmxw), collapse = "     "), con)
  writeLines("fnoptw", con)
  writeLines(paste(sprintf("%.3f",fnoptw), collapse = "     "), con)
  # writeLines("diagstart", con)
  # writeLines(paste(sprintf("%.3f",diagstart), collapse = "     "), con)
  # writeLines("diagend", con)
  # writeLines(paste(sprintf("%.3f",diagend), collapse = "     "), con)
  # writeLines("ndiagpt", con)
  # writeLines(paste(sprintf("%.3f",ndiagpt), collapse = "     "), con)
  # writeLines("nfreq", con)
  # writeLines(paste(sprintf("%.3f",nfreq), collapse = "     "), con)
  writeLines("imetyear", con)
  writeLines(paste(sprintf("%.3f",imetyear), collapse = "     "), con)
  writeLines("dmetyear", con)
  writeLines(paste(sprintf("%.3f",dmetyear), collapse = "     "), con)
  writeLines("imetend", con)
  writeLines(paste(sprintf("%.3f",imetend), collapse = "     "), con)
  writeLines("dmetend", con)
  writeLines(paste(sprintf("%.3f",dmetend), collapse = "     "), con)
  writeLines("ginvap", con)
  writeLines(paste(sprintf("%.3f",ginvap), collapse = "     "), con)
  writeLines("gsuvap", con)
  writeLines(paste(sprintf("%.3f",gsuvap), collapse = "     "), con)
  writeLines("gtrans", con)
  writeLines(paste(sprintf("%.3f",gtrans), collapse = "     "), con)
  writeLines("gtransu", con)
  writeLines(paste(sprintf("%.3f",gtransu), collapse = "     "), con)
  writeLines("gtransl", con)
  writeLines(paste(sprintf("%.3f",gtransl), collapse = "     "), con)
  writeLines("grunof", con)
  writeLines(paste(sprintf("%.3f",grunof), collapse = "     "), con)
  writeLines("gdrain", con)
  writeLines(paste(sprintf("%.3f",gdrain), collapse = "     "), con)
  writeLines("gadjust", con)
  writeLines(paste(sprintf("%.3f",gadjust), collapse = "     "), con)
  writeLines("wtot", con)
  writeLines(paste(sprintf("%.3f",wtot), collapse = "     "), con)
  # writeLines("lworkdir", con)
  # writeLines(paste(sprintf("%.3f",lworkdir), collapse = "     "), con)
  writeLines("storedn", con)
  writeLines(paste(sprintf("%.3f",storedn), collapse = "     "), con)
  writeLines("yrleach", con)
  writeLines(paste(sprintf("%.3f",yrleach), collapse = "     "), con)
  writeLines("aplantn", con)
  writeLines(paste(sprintf("%.3f",aplantn), collapse = "     "), con)
  writeLines("cplantn", con)
  writeLines(paste(sprintf("%.3f",cplantn), collapse = "     "), con)
  writeLines("totmin", con)
  writeLines(paste(sprintf("%.3f",totmin), collapse = "     "), con)
  writeLines("totimm", con)
  writeLines(paste(sprintf("%.3f",totimm), collapse = "     "), con)
  writeLines("totnrel", con)
  writeLines(paste(sprintf("%.3f",totnrel), collapse = "     "), con)
  writeLines("ctot", con)
  writeLines(paste(sprintf("%.3f",ctot), collapse = "     "), con)
  writeLines("ctoti", con)
  writeLines(paste(sprintf("%.3f",ctoti), collapse = "     "), con)
  writeLines("ftot", con)
  writeLines(paste(sprintf("%.3f",ftot), collapse = "     "), con)
  writeLines("tsinp", con)
  writeLines(paste(sprintf("%.3f",tsinp), collapse = "     "), con)
  writeLines("tslay", con)
  writeLines(paste(sprintf("%.3f",tslay), collapse = "     "), con)
  writeLines("tsnimm", con)
  writeLines(paste(sprintf("%.3f",tsnimm), collapse = "     "), con)
  writeLines("tsnmob", con)
  writeLines(paste(sprintf("%.3f",tsnmob), collapse = "     "), con)
  writeLines("taninp", con)
  writeLines(paste(sprintf("%.3f",taninp), collapse = "     "), con)
  writeLines("dtnleach", con)
  writeLines(paste(sprintf("%.3f",dtnleach), collapse = "     "), con)
  writeLines("dnileach", con)
  writeLines(paste(sprintf("%.3f",dnileach), collapse = "     "), con)
  writeLines("tpnuptake", con)
  writeLines(paste(sprintf("%.3f",tpnuptake), collapse = "     "), con)
  writeLines("totnvegn", con)
  writeLines(paste(sprintf("%.3f",totnvegn), collapse = "     "), con)
  writeLines("drntot", con)
  writeLines(paste(sprintf("%.3f",drntot), collapse = "     "), con)
  writeLines("ddrn", con)
  writeLines(paste(sprintf("%.3f",ddrn), collapse = "     "), con)
  writeLines("concn", con)
  writeLines(paste(sprintf("%.3f",concn), collapse = "     "), con)
  writeLines("assimn", con)
  writeLines(paste(sprintf("%.3f",assimn), collapse = "     "), con)
  writeLines("ydeposn", con)
  writeLines(paste(sprintf("%.3f",ydeposn), collapse = "     "), con)
  writeLines("yfixsoin", con)
  writeLines(paste(sprintf("%.3f",yfixsoin), collapse = "     "), con)
  writeLines("yno3leach", con)
  writeLines(paste(sprintf("%.3f",yno3leach), collapse = "     "), con)
  writeLines("snbalance", con)
  writeLines(paste(sprintf("%.3f",snbalance), collapse = "     "), con)
  writeLines("fixsoin", con)
  writeLines(paste(sprintf("%.3f",fixsoin), collapse = "     "), con)
  writeLines("totnuptake", con)
  writeLines(paste(sprintf("%.3f",totnuptake), collapse = "     "), con)
  writeLines("stressn", con)
  writeLines(paste(sprintf("%.3f",stressn), collapse = "     "), con)
  writeLines("totnfix", con)
  writeLines(paste(sprintf("%.3f",totnfix), collapse = "     "), con)
  writeLines("fixn", con)
  writeLines(paste(sprintf("%.3f",fixn), collapse = "     "), con)
  writeLines("fertnitro", con)
  writeLines(paste(sprintf("%.3f",fertnitro), collapse = "     "), con)
  writeLines("epsilon", con)
  writeLines(paste(sprintf("%.3f",epsilon), collapse = "     "), con)
  writeLines("dtime", con)
  writeLines(paste(sprintf("%.3f",dtime), collapse = "     "), con)
  writeLines("stef", con)
  writeLines(paste(sprintf("%.3f",stef), collapse = "     "), con)
  writeLines("vonk", con)
  writeLines(paste(sprintf("%.3f",vonk), collapse = "     "), con)
  writeLines("ustar", con)
  writeLines(paste(sprintf("%.3f",ustar), collapse = "     "), con)
  writeLines("grav", con)
  writeLines(paste(sprintf("%.3f",grav), collapse = "     "), con)
  writeLines("tmelt", con)
  writeLines(paste(sprintf("%.3f",tmelt), collapse = "     "), con)
  writeLines("hfus", con)
  writeLines(paste(sprintf("%.3f",hfus), collapse = "     "), con)
  writeLines("hvap", con)
  writeLines(paste(sprintf("%.3f",hvap), collapse = "     "), con)
  writeLines("hsub", con)
  writeLines(paste(sprintf("%.3f",hsub), collapse = "     "), con)
  writeLines("ch2o", con)
  writeLines(paste(sprintf("%.3f",ch2o), collapse = "     "), con)
  writeLines("cice", con)
  writeLines(paste(sprintf("%.3f",cice), collapse = "     "), con)
  writeLines("cair", con)
  writeLines(paste(sprintf("%.3f",cair), collapse = "     "), con)
  writeLines("cvap", con)
  writeLines(paste(sprintf("%.3f",cvap), collapse = "     "), con)
  writeLines("rair", con)
  writeLines(paste(sprintf("%.3f",rair), collapse = "     "), con)
  writeLines("rvap", con)
  writeLines(paste(sprintf("%.3f",rvap), collapse = "     "), con)
  writeLines("cappa", con)
  writeLines(paste(sprintf("%.3f",cappa), collapse = "     "), con)
  writeLines("rhow", con)
  writeLines(paste(sprintf("%.3f",rhow), collapse = "     "), con)
  writeLines("garea", con)
  writeLines(paste(sprintf("%.3f",garea), collapse = "     "), con)
  writeLines("vzero", con)
  writeLines(paste(sprintf("%.3f",vzero), collapse = "     "), con)
  writeLines("lat_npoi", con)
  writeLines(paste(sprintf("%.3f",lat_npoi), collapse = "     "), con)
  writeLines("lon_npoi", con)
  writeLines(paste(sprintf("%.3f",lon_npoi), collapse = "     "), con)
  writeLines("ndaypy", con)
  writeLines(paste(sprintf("%.3f",ndaypy), collapse = "     "), con)
  writeLines("nlonsub", con)
  writeLines(paste(sprintf("%.3f",nlonsub), collapse = "     "), con)
  writeLines("nlatsub", con)
  writeLines(paste(sprintf("%.3f",nlatsub), collapse = "     "), con)
  writeLines("ndaypm", con)
  writeLines(paste(sprintf("%.3f",ndaypm), collapse = "     "), con)
  writeLines("tau15", con)
  writeLines(paste(sprintf("%.3f",tau15), collapse = "     "), con)
  writeLines("kc15", con)
  writeLines(paste(sprintf("%.3f",kc15), collapse = "     "), con)
  writeLines("ko15", con)
  writeLines(paste(sprintf("%.3f",ko15), collapse = "     "), con)
  writeLines("cimax", con)
  writeLines(paste(sprintf("%.3f",cimax), collapse = "     "), con)
  writeLines("vmax_pft", con)
  writeLines(paste(sprintf("%.3f",vmax_pft), collapse = "     "), con)
  writeLines("alpha", con)
  writeLines(paste(sprintf("%.3f", alpha), collapse = "     "), con)
  writeLines("beta", con)
  writeLines(paste(sprintf("%.3f",   beta ), collapse = "     "), con)
  writeLines("theta", con)
  writeLines(paste(sprintf("%.3f",    theta), collapse = "     "), con)
  writeLines("gamma", con)
  writeLines(paste(sprintf("%.3f",     gamma ), collapse = "     "), con)
  writeLines("coefm", con)
  writeLines(paste(sprintf("%.3f",     coefm ), collapse = "     "), con)
  writeLines("coefb", con)
  writeLines(paste(sprintf("%.3f",  coefb  ), collapse = "     "), con)
  writeLines("gsmin", con)
  writeLines(paste(sprintf("%.3f",  gsmin ), collapse = "     "), con)
  writeLines("lotemp", con)
  writeLines(paste(sprintf("%.3f",lotemp), collapse = "     "), con)
  writeLines("hitemp", con)
  writeLines(paste(sprintf("%.3f",hitemp), collapse = "     "), con)
  writeLines("drought", con)
  writeLines(paste(sprintf("%.3f",drought), collapse = "     "), con)
  writeLines("f1", con)
  writeLines(paste(sprintf("%.3f",f1), collapse = "     "), con)
  writeLines("f2", con)
  writeLines(paste(sprintf("%.3f",f2), collapse = "     "), con)
  writeLines("tauleaf", con)
  writeLines(paste(sprintf("%.3f",tauleaf), collapse = "     "), con)
  writeLines("tauroot", con)
  writeLines(paste(sprintf("%.3f",tauroot), collapse = "     "), con)
  writeLines("tauwood", con)
  writeLines(paste(sprintf("%.3f",tauwood), collapse = "     "), con)
  writeLines("tauwood0", con)
  writeLines(paste(sprintf("%.3f",tauwood0), collapse = "     "), con)
  writeLines("plai_init", con)
  writeLines(paste(sprintf("%.3f",plai_init), collapse = "     "), con)
  writeLines("plaiupper", con)
  writeLines(paste(sprintf("%.3f",plaiupper), collapse = "     "), con)
  writeLines("plailower", con)
  writeLines(paste(sprintf("%.3f",plailower), collapse = "     "), con)
  writeLines("xminlai", con)
  writeLines(paste(sprintf("%.3f",xminlai), collapse = "     "), con)
  writeLines("sapfrac_init", con)
  writeLines(paste(sprintf("%.3f",sapfrac_init), collapse = "     "), con)
  writeLines("beta1", con)
  writeLines(paste(sprintf("%.3f",beta1), collapse = "     "), con)
  writeLines("beta2", con)
  writeLines(paste(sprintf("%.3f",beta2), collapse = "     "), con)
  writeLines("TminL", con)
  writeLines(paste(sprintf("%.3f",TminL), collapse = "     "), con)
  writeLines("TminU", con)
  writeLines(paste(sprintf("%.3f",TminU), collapse = "     "), con)
  writeLines("Twarm", con)
  writeLines(paste(sprintf("%.3f",Twarm), collapse = "     "), con)
  writeLines("GDD", con)
  writeLines(paste(sprintf("%.3f",GDD), collapse = "     "), con)
  writeLines("z0sno", con)
  writeLines(paste(sprintf("%.3f",z0sno), collapse = "     "), con)
  writeLines("rhos", con)
  writeLines(paste(sprintf("%.3f",rhos), collapse = "     "), con)
  writeLines("consno", con)
  writeLines(paste(sprintf("%.3f",consno), collapse = "     "), con)
  writeLines("hsnotop", con)
  writeLines(paste(sprintf("%.3f",hsnotop), collapse = "     "), con)
  writeLines("hsnomin", con)
  writeLines(paste(sprintf("%.3f",hsnomin), collapse = "     "), con)
  writeLines("fimin", con)
  writeLines(paste(sprintf("%.3f",fimin), collapse = "     "), con)
  writeLines("fimax", con)
  writeLines(paste(sprintf("%.3f",fimax), collapse = "     "), con)
  writeLines("fi", con)
  writeLines(paste(sprintf("%.3f",fi), collapse = "     "), con)
  writeLines("tsno", con)
  writeLines(paste(sprintf("%.3f",tsno), collapse = "     "), con)
  writeLines("hsno", con)
  writeLines(paste(sprintf("%.3f",hsno), collapse = "     "), con)
  writeLines("wpudmax", con)
  writeLines(paste(sprintf("%.3f",wpudmax), collapse = "     "), con)
  writeLines("zwpmax", con)
  writeLines(paste(sprintf("%.3f",zwpmax), collapse = "     "), con)
  writeLines("bperm", con)
  writeLines(paste(sprintf("%.3f",bperm), collapse = "     "), con)
  writeLines("wpud", con)
  writeLines(paste(sprintf("%.3f",wpud), collapse = "     "), con)
  writeLines("wipud", con)
  writeLines(paste(sprintf("%.3f",wipud), collapse = "     "), con)
  writeLines("z0soi", con)
  writeLines(paste(sprintf("%.3f",z0soi), collapse = "     "), con)
  writeLines("albsav", con)
  writeLines(paste(sprintf("%.3f",albsav), collapse = "     "), con)
  writeLines("albsan", con)
  writeLines(paste(sprintf("%.3f",albsan), collapse = "     "), con)
  writeLines("stresstl", con)
  writeLines(paste(sprintf("%.3f",stresstl), collapse = "     "), con)
  writeLines("stresstu", con)
  writeLines(paste(sprintf("%.3f",stresstu), collapse = "     "), con)
  writeLines("heati", con)
  writeLines(paste(sprintf("%.3f",heati), collapse = "     "), con)
  writeLines("heatg", con)
  writeLines(paste(sprintf("%.3f",heatg), collapse = "     "), con)
  writeLines("soihfl", con)
  writeLines(paste(sprintf("%.3f",soihfl), collapse = "     "), con)
  writeLines("hvasug", con)
  writeLines(paste(sprintf("%.3f",hvasug), collapse = "     "), con)
  writeLines("hvasui", con)
  writeLines(paste(sprintf("%.3f",hvasui), collapse = "     "), con)
  writeLines("tg", con)
  writeLines(paste(sprintf("%.3f",tg), collapse = "     "), con)
  writeLines("ti", con)
  writeLines(paste(sprintf("%.3f",ti), collapse = "     "), con)
  writeLines("fwtop", con)
  writeLines(paste(sprintf("%.3f",fwtop), collapse = "     "), con)
  writeLines("fwpud", con)
  writeLines(paste(sprintf("%.3f",fwpud), collapse = "     "), con)
  writeLines("deposn", con)
  writeLines(paste(sprintf("%.3f",deposn), collapse = "     "), con)
  writeLines("hsoi", con)
  writeLines(paste(sprintf("%.3f",hsoi), collapse = "     "), con)
  writeLines("tsoi", con)
  writeLines(paste(sprintf("%.3f",tsoi), collapse = "     "), con)
  writeLines("wsoi", con)
  writeLines(paste(sprintf("%.3f",wsoi), collapse = "     "), con)
  writeLines("wisoi", con)
  writeLines(paste(sprintf("%.3f",wisoi), collapse = "     "), con)
  writeLines("consoi", con)
  writeLines(paste(sprintf("%.3f",consoi), collapse = "     "), con)
  writeLines("csoi", con)
  writeLines(paste(sprintf("%.3f",csoi), collapse = "     "), con)
  writeLines("hydraul", con)
  writeLines(paste(sprintf("%.3f",hydraul), collapse = "     "), con)
  writeLines("suction", con)
  writeLines(paste(sprintf("%.3f",suction), collapse = "     "), con)
  writeLines("bex", con)
  writeLines(paste(sprintf("%.3f",bex), collapse = "     "), con)
  writeLines("sfield", con)
  writeLines(paste(sprintf("%.3f",sfield), collapse = "     "), con)
  writeLines("swilt", con)
  writeLines(paste(sprintf("%.3f",swilt), collapse = "     "), con)
  writeLines("rhosoi", con)
  writeLines(paste(sprintf("%.3f",rhosoi), collapse = "     "), con)
  writeLines("poros", con)
  writeLines(paste(sprintf("%.3f",poros), collapse = "     "), con)
  writeLines("porosflo", con)
  writeLines(paste(sprintf("%.3f",porosflo), collapse = "     "), con)
  writeLines("sand", con)
  writeLines(paste(sprintf("%.3f",sand), collapse = "     "), con)
  writeLines("clay", con)
  writeLines(paste(sprintf("%.3f",clay), collapse = "     "), con)
  writeLines("stressl", con)
  writeLines(paste(sprintf("%.3f",stressl), collapse = "     "), con)
  writeLines("stressu", con)
  writeLines(paste(sprintf("%.3f",stressu), collapse = "     "), con)
  writeLines("upsoiu", con)
  writeLines(paste(sprintf("%.3f",upsoiu), collapse = "     "), con)
  writeLines("upsoil", con)
  writeLines(paste(sprintf("%.3f",upsoil), collapse = "     "), con)
  writeLines("soisand", con)
  writeLines(paste(sprintf("%.3f",soisand), collapse = "     "), con)
  writeLines("soiclay", con)
  writeLines(paste(sprintf("%.3f",soiclay), collapse = "     "), con)
  writeLines("domtext", con)
  writeLines(paste(sprintf("%.3f",domtext), collapse = "     "), con)
  writeLines("fracsand", con)
  writeLines(paste(sprintf("%.3f",fracsand), collapse = "     "), con)
  writeLines("fracsilt", con)
  writeLines(paste(sprintf("%.3f",fracsilt), collapse = "     "), con)
  writeLines("fracclay", con)
  writeLines(paste(sprintf("%.3f",fracclay), collapse = "     "), con)
  writeLines("cpwf", con)
  writeLines(paste(sprintf("%.3f",cpwf), collapse = "     "), con)
  writeLines("fwpudtot", con)
  writeLines(paste(sprintf("%.3f",fwpudtot), collapse = "     "), con)
  writeLines("swater", con)
  writeLines(paste(sprintf("%.3f",swater), collapse = "     "), con)
  writeLines("sice", con)
  writeLines(paste(sprintf("%.3f",sice), collapse = "     "), con)
  writeLines("hflo", con)
  writeLines(paste(sprintf("%.3f",hflo), collapse = "     "), con)
  writeLines("ibex", con)
  writeLines(paste(sprintf("%.3f",ibex), collapse = "     "), con)
  writeLines("nslaym", con)
  writeLines(paste(sprintf("%.3f",nslaym), collapse = "     "), con)
  writeLines("qglif", con)
  writeLines(paste(sprintf("%.3f",qglif), collapse = "     "), con)
  writeLines("pmsoil", con)
  writeLines(paste(sprintf("%.3f",pmsoil), collapse = "     "), con)
  writeLines("pmsoln", con)
  writeLines(paste(sprintf("%.3f",pmsoln), collapse = "     "), con)
  writeLines("pcsoln", con)
  writeLines(paste(sprintf("%.3f",pcsoln), collapse = "     "), con)
  writeLines("smsoil", con)
  writeLines(paste(sprintf("%.3f",smsoil), collapse = "     "), con)
  writeLines("smsoln", con)
  writeLines(paste(sprintf("%.3f",smsoln), collapse = "     "), con)
  writeLines("fout", con)
  writeLines(paste(sprintf("%.3f",fout), collapse = "     "), con)
  writeLines("nout", con)
  writeLines(paste(sprintf("%.3f",nout), collapse = "     "), con)
  writeLines("csoln", con)
  writeLines(paste(sprintf("%.3f",csoln), collapse = "     "), con)
  writeLines("tnuptake", con)
  writeLines(paste(sprintf("%.3f",tnuptake), collapse = "     "), con)
  writeLines("anuptake", con)
  writeLines(paste(sprintf("%.3f",anuptake), collapse = "     "), con)
  writeLines("wflo", con)
  writeLines(paste(sprintf("%.3f",wflo), collapse = "     "), con)
  writeLines("ndtimes", con)
  writeLines(paste(sprintf("%.3f",ndtimes), collapse = "     "), con)
  writeLines("nmtimes", con)
  writeLines(paste(sprintf("%.3f",nmtimes), collapse = "     "), con)
  writeLines("nytimes", con)
  writeLines(paste(sprintf("%.3f",nytimes), collapse = "     "), con)
  writeLines("idoy", con)
  writeLines(paste(sprintf("%.3f",idoy), collapse = "     "), con)
  writeLines("adrain", con)
  writeLines(paste(sprintf("%.3f",adrain), collapse = "     "), con)
  writeLines("adsnow", con)
  writeLines(paste(sprintf("%.3f",adsnow), collapse = "     "), con)
  writeLines("adaet", con)
  writeLines(paste(sprintf("%.3f",adaet), collapse = "     "), con)
  writeLines("adtrans", con)
  writeLines(paste(sprintf("%.3f",adtrans), collapse = "     "), con)
  writeLines("adevap", con)
  writeLines(paste(sprintf("%.3f",adevap), collapse = "     "), con)
  writeLines("adtratio", con)
  writeLines(paste(sprintf("%.3f",adtratio), collapse = "     "), con)
  writeLines("adtrunoff", con)
  writeLines(paste(sprintf("%.3f",adtrunoff), collapse = "     "), con)
  writeLines("adsrunoff", con)
  writeLines(paste(sprintf("%.3f",adsrunoff), collapse = "     "), con)
  writeLines("addrainage", con)
  writeLines(paste(sprintf("%.3f",addrainage), collapse = "     "), con)
  writeLines("adrh", con)
  writeLines(paste(sprintf("%.3f",adrh), collapse = "     "), con)
  writeLines("adud", con)
  writeLines(paste(sprintf("%.3f",adud), collapse = "     "), con)
  writeLines("adsnod", con)
  writeLines(paste(sprintf("%.3f",adsnod), collapse = "     "), con)
  writeLines("adsnof", con)
  writeLines(paste(sprintf("%.3f",adsnof), collapse = "     "), con)
  writeLines("adwsoi", con)
  writeLines(paste(sprintf("%.3f",adwsoi), collapse = "     "), con)
  writeLines("adwisoi", con)
  writeLines(paste(sprintf("%.3f",adwisoi), collapse = "     "), con)
  writeLines("adtsoi", con)
  writeLines(paste(sprintf("%.3f",adtsoi), collapse = "     "), con)
  writeLines("adwsoic", con)
  writeLines(paste(sprintf("%.3f",adwsoic), collapse = "     "), con)
  writeLines("adtsoic", con)
  writeLines(paste(sprintf("%.3f",adtsoic), collapse = "     "), con)
  writeLines("adco2mic", con)
  writeLines(paste(sprintf("%.3f",adco2mic), collapse = "     "), con)
  writeLines("adco2root", con)
  writeLines(paste(sprintf("%.3f",adco2root), collapse = "     "), con)
  writeLines("adco2soi", con)
  writeLines(paste(sprintf("%.3f",adco2soi), collapse = "     "), con)
  writeLines("adco2ratio", con)
  writeLines(paste(sprintf("%.3f",adco2ratio), collapse = "     "), con)
  writeLines("adnmintot", con)
  writeLines(paste(sprintf("%.3f",adnmintot), collapse = "     "), con)
  writeLines("adtlaysoi", con)
  writeLines(paste(sprintf("%.3f",adtlaysoi), collapse = "     "), con)
  writeLines("adwlaysoi", con)
  writeLines(paste(sprintf("%.3f",adwlaysoi), collapse = "     "), con)
  writeLines("adneetot", con)
  writeLines(paste(sprintf("%.3f",adneetot), collapse = "     "), con)
  writeLines("adwsoilay", con)
  writeLines(paste(sprintf("%.3f",adwsoilay), collapse = "     "), con)
  writeLines("adwisoilay", con)
  writeLines(paste(sprintf("%.3f",adwisoilay), collapse = "     "), con)
  writeLines("adtsoilay", con)
  writeLines(paste(sprintf("%.3f",adtsoilay), collapse = "     "), con)
  writeLines("adupsoil", con)
  writeLines(paste(sprintf("%.3f",adupsoil), collapse = "     "), con)
  writeLines("adcsoln", con)
  writeLines(paste(sprintf("%.3f",adcsoln), collapse = "     "), con)
  writeLines("amtemp", con)
  writeLines(paste(sprintf("%.3f",amtemp), collapse = "     "), con)
  writeLines("amrain", con)
  writeLines(paste(sprintf("%.3f",amrain), collapse = "     "), con)
  writeLines("amsnow", con)
  writeLines(paste(sprintf("%.3f",amsnow), collapse = "     "), con)
  writeLines("amcloud", con)
  writeLines(paste(sprintf("%.3f",amcloud), collapse = "     "), con)
  writeLines("amrh", con)
  writeLines(paste(sprintf("%.3f",amrh), collapse = "     "), con)
  writeLines("amqa", con)
  writeLines(paste(sprintf("%.3f",amqa), collapse = "     "), con)
  writeLines("amaet", con)
  writeLines(paste(sprintf("%.3f",amaet), collapse = "     "), con)
  writeLines("amtrans", con)
  writeLines(paste(sprintf("%.3f",amtrans), collapse = "     "), con)
  writeLines("amtratio", con)
  writeLines(paste(sprintf("%.3f",amtratio), collapse = "     "), con)
  writeLines("amtrunoff", con)
  writeLines(paste(sprintf("%.3f",amtrunoff), collapse = "     "), con)
  writeLines("amsrunoff", con)
  writeLines(paste(sprintf("%.3f",amsrunoff), collapse = "     "), con)
  writeLines("amdrainage", con)
  writeLines(paste(sprintf("%.3f",amdrainage), collapse = "     "), con)
  writeLines("amtotnleach", con)
  writeLines(paste(sprintf("%.3f",amtotnleach), collapse = "     "), con)
  writeLines("amno3leach", con)
  writeLines(paste(sprintf("%.3f",amno3leach), collapse = "     "), con)
  writeLines("amwsoi", con)
  writeLines(paste(sprintf("%.3f",amwsoi), collapse = "     "), con)
  writeLines("amwisoi", con)
  writeLines(paste(sprintf("%.3f",amwisoi), collapse = "     "), con)
  writeLines("amvwc", con)
  writeLines(paste(sprintf("%.3f",amvwc), collapse = "     "), con)
  writeLines("amawc", con)
  writeLines(paste(sprintf("%.3f",amawc), collapse = "     "), con)
  writeLines("amtsoi", con)
  writeLines(paste(sprintf("%.3f",amtsoi), collapse = "     "), con)
  writeLines("amsnod", con)
  writeLines(paste(sprintf("%.3f",amsnod), collapse = "     "), con)
  writeLines("amsnof", con)
  writeLines(paste(sprintf("%.3f",amsnof), collapse = "     "), con)
  writeLines("amlaiu", con)
  writeLines(paste(sprintf("%.3f",amlaiu), collapse = "     "), con)
  writeLines("amlail", con)
  writeLines(paste(sprintf("%.3f",amlail), collapse = "     "), con)
  writeLines("amsolar", con)
  writeLines(paste(sprintf("%.3f",amsolar), collapse = "     "), con)
  writeLines("rnet", con)
  writeLines(paste(sprintf("%.3f",rnet), collapse = "     "), con)
  writeLines("amalbedo", con)
  writeLines(paste(sprintf("%.3f",amalbedo), collapse = "     "), con)
  writeLines("amirdown", con)
  writeLines(paste(sprintf("%.3f",amirdown), collapse = "     "), con)
  writeLines("amirup", con)
  writeLines(paste(sprintf("%.3f",amirup), collapse = "     "), con)
  writeLines("amsens", con)
  writeLines(paste(sprintf("%.3f",amsens), collapse = "     "), con)
  writeLines("amlatent", con)
  writeLines(paste(sprintf("%.3f",amlatent), collapse = "     "), con)
  writeLines("amnpptot", con)
  writeLines(paste(sprintf("%.3f",amnpptot), collapse = "     "), con)
  writeLines("amneetot", con)
  writeLines(paste(sprintf("%.3f",amneetot), collapse = "     "), con)
  writeLines("amco2mic", con)
  writeLines(paste(sprintf("%.3f",amco2mic), collapse = "     "), con)
  writeLines("amco2root", con)
  writeLines(paste(sprintf("%.3f",amco2root), collapse = "     "), con)
  writeLines("amco2soi", con)
  writeLines(paste(sprintf("%.3f",amco2soi), collapse = "     "), con)
  writeLines("amco2ratio", con)
  writeLines(paste(sprintf("%.3f",amco2ratio), collapse = "     "), con)
  writeLines("amnmintot", con)
  writeLines(paste(sprintf("%.3f",amnmintot), collapse = "     "), con)
  writeLines("amnpp", con)
  writeLines(paste(sprintf("%.3f",amnpp), collapse = "     "), con)
  writeLines("adnpp", con)
  writeLines(paste(sprintf("%.3f",adnpp), collapse = "     "), con)
  writeLines("ayprcp", con)
  writeLines(paste(sprintf("%.3f",ayprcp), collapse = "     "), con)
  writeLines("ayaet", con)
  writeLines(paste(sprintf("%.3f",ayaet), collapse = "     "), con)
  writeLines("aytrans", con)
  writeLines(paste(sprintf("%.3f",aytrans), collapse = "     "), con)
  writeLines("aytrunoff", con)
  writeLines(paste(sprintf("%.3f",aytrunoff), collapse = "     "), con)
  writeLines("aysrunoff", con)
  writeLines(paste(sprintf("%.3f",aysrunoff), collapse = "     "), con)
  writeLines("aydrainage", con)
  writeLines(paste(sprintf("%.3f",aydrainage), collapse = "     "), con)
  writeLines("aydwtot", con)
  writeLines(paste(sprintf("%.3f",aydwtot), collapse = "     "), con)
  writeLines("aywsoi", con)
  writeLines(paste(sprintf("%.3f",aywsoi), collapse = "     "), con)
  writeLines("aywisoi", con)
  writeLines(paste(sprintf("%.3f",aywisoi), collapse = "     "), con)
  writeLines("ayvwc", con)
  writeLines(paste(sprintf("%.3f",ayvwc), collapse = "     "), con)
  writeLines("ayawc", con)
  writeLines(paste(sprintf("%.3f",ayawc), collapse = "     "), con)
  writeLines("aytsoi", con)
  writeLines(paste(sprintf("%.3f",aytsoi), collapse = "     "), con)
  writeLines("ayrratio", con)
  writeLines(paste(sprintf("%.3f",ayrratio), collapse = "     "), con)
  writeLines("aytratio", con)
  writeLines(paste(sprintf("%.3f",aytratio), collapse = "     "), con)
  writeLines("aysolar", con)
  writeLines(paste(sprintf("%.3f",aysolar), collapse = "     "), con)
  writeLines("ayalbedo", con)
  writeLines(paste(sprintf("%.3f",ayalbedo), collapse = "     "), con)
  writeLines("ayirdown", con)
  writeLines(paste(sprintf("%.3f",ayirdown), collapse = "     "), con)
  writeLines("ayirup", con)
  writeLines(paste(sprintf("%.3f",ayirup), collapse = "     "), con)
  writeLines("aysens", con)
  writeLines(paste(sprintf("%.3f",aysens), collapse = "     "), con)
  writeLines("aylatent", con)
  writeLines(paste(sprintf("%.3f",aylatent), collapse = "     "), con)
  writeLines("aystresstu", con)
  writeLines(paste(sprintf("%.3f",aystresstu), collapse = "     "), con)
  writeLines("aystresstl", con)
  writeLines(paste(sprintf("%.3f",aystresstl), collapse = "     "), con)
  writeLines("ayanpptot", con)
  writeLines(paste(sprintf("%.3f",ayanpptot), collapse = "     "), con)
  writeLines("aynpptot", con)
  writeLines(paste(sprintf("%.3f",aynpptot), collapse = "     "), con)
  writeLines("aygpptot", con)
  writeLines(paste(sprintf("%.3f",aygpptot), collapse = "     "), con)
  writeLines("ayalit", con)
  writeLines(paste(sprintf("%.3f",ayalit), collapse = "     "), con)
  writeLines("ayblit", con)
  writeLines(paste(sprintf("%.3f",ayblit), collapse = "     "), con)
  writeLines("aycsoi", con)
  writeLines(paste(sprintf("%.3f",aycsoi), collapse = "     "), con)
  writeLines("aycmic", con)
  writeLines(paste(sprintf("%.3f",aycmic), collapse = "     "), con)
  writeLines("ayanlit", con)
  writeLines(paste(sprintf("%.3f",ayanlit), collapse = "     "), con)
  writeLines("aybnlit", con)
  writeLines(paste(sprintf("%.3f",aybnlit), collapse = "     "), con)
  writeLines("aynsoi", con)
  writeLines(paste(sprintf("%.3f",aynsoi), collapse = "     "), con)
  writeLines("ynleach", con)
  writeLines(paste(sprintf("%.3f",ynleach), collapse = "     "), con)
  writeLines("ayneetot", con)
  writeLines(paste(sprintf("%.3f",ayneetot), collapse = "     "), con)
  writeLines("ayco2mic", con)
  writeLines(paste(sprintf("%.3f",ayco2mic), collapse = "     "), con)
  writeLines("ayco2root", con)
  writeLines(paste(sprintf("%.3f",ayco2root), collapse = "     "), con)
  writeLines("ayco2soi", con)
  writeLines(paste(sprintf("%.3f",ayco2soi), collapse = "     "), con)
  writeLines("aynmintot", con)
  writeLines(paste(sprintf("%.3f",aynmintot), collapse = "     "), con)
  writeLines("aymintot", con)
  writeLines(paste(sprintf("%.3f",aymintot), collapse = "     "), con)
  writeLines("ayimmtot", con)
  writeLines(paste(sprintf("%.3f",ayimmtot), collapse = "     "), con)
  writeLines("aynreltot", con)
  writeLines(paste(sprintf("%.3f",aynreltot), collapse = "     "), con)
  writeLines("ayrootbio", con)
  writeLines(paste(sprintf("%.3f",ayrootbio), collapse = "     "), con)
  writeLines("ayanpp", con)
  writeLines(paste(sprintf("%.3f",ayanpp), collapse = "     "), con)
  writeLines("aynpp", con)
  writeLines(paste(sprintf("%.3f",aynpp), collapse = "     "), con)
  writeLines("aygpp", con)
  writeLines(paste(sprintf("%.3f",aygpp), collapse = "     "), con)
  writeLines("aybprod", con)
  writeLines(paste(sprintf("%.3f",aybprod), collapse = "     "), con)
  writeLines("ayabprod", con)
  writeLines(paste(sprintf("%.3f",ayabprod), collapse = "     "), con)
  writeLines("ayrprod", con)
  writeLines(paste(sprintf("%.3f",ayrprod), collapse = "     "), con)
  writeLines("aylprod", con)
  writeLines(paste(sprintf("%.3f",aylprod), collapse = "     "), con)
  writeLines("a10td", con)
  writeLines(paste(sprintf("%.3f",a10td), collapse = "     "), con)
  writeLines("a10ts", con)
  writeLines(paste(sprintf("%.3f",a10ts), collapse = "     "), con)
  writeLines("a5td", con)
  writeLines(paste(sprintf("%.3f",a5td), collapse = "     "), con)
  writeLines("a5tmin", con)
  writeLines(paste(sprintf("%.3f",a5tmin), collapse = "     "), con)
  writeLines("a10tmin", con)
  writeLines(paste(sprintf("%.3f",a10tmin), collapse = "     "), con)
  writeLines("a10ancub", con)
  writeLines(paste(sprintf("%.3f",a10ancub), collapse = "     "), con)
  writeLines("a10ancuc", con)
  writeLines(paste(sprintf("%.3f",a10ancuc), collapse = "     "), con)
  writeLines("a10ancls", con)
  writeLines(paste(sprintf("%.3f",a10ancls), collapse = "     "), con)
  writeLines("a10ancl3", con)
  writeLines(paste(sprintf("%.3f",a10ancl3), collapse = "     "), con)
  writeLines("a10ancl4", con)
  writeLines(paste(sprintf("%.3f",a10ancl4), collapse = "     "), con)
  writeLines("a10ancc3", con)
  writeLines(paste(sprintf("%.3f",a10ancc3), collapse = "     "), con)
  writeLines("a10ancc4", con)
  writeLines(paste(sprintf("%.3f",a10ancc4), collapse = "     "), con)
  writeLines("a10scalparamu", con)
  writeLines(paste(sprintf("%.3f",a10scalparamu), collapse = "     "), con)
  writeLines("a10scalparaml", con)
  writeLines(paste(sprintf("%.3f",a10scalparaml), collapse = "     "), con)
  writeLines("a10daylightu", con)
  writeLines(paste(sprintf("%.3f",a10daylightu), collapse = "     "), con)
  writeLines("a10daylightl", con)
  writeLines(paste(sprintf("%.3f",a10daylightl), collapse = "     "), con)
  writeLines("texdat", con)
  writeLines(paste(sprintf("%.3f",texdat), collapse = "     "), con)
  writeLines("porosdat", con)
  writeLines(paste(sprintf("%.3f",porosdat), collapse = "     "), con)
  writeLines("sfielddat", con)
  writeLines(paste(sprintf("%.3f",sfielddat), collapse = "     "), con)
  writeLines("swiltdat", con)
  writeLines(paste(sprintf("%.3f",swiltdat), collapse = "     "), con)
  writeLines("bexdat", con)
  writeLines(paste(sprintf("%.3f",bexdat), collapse = "     "), con)
  writeLines("suctiondat", con)
  writeLines(paste(sprintf("%.3f",suctiondat), collapse = "     "), con)
  writeLines("hydrauldat", con)
  writeLines(paste(sprintf("%.3f",hydrauldat), collapse = "     "), con)
  writeLines("onflagu", con)
  writeLines(paste(sprintf("%.3f",onflagu), collapse = "     "), con)
  writeLines("onflagl3", con)
  writeLines(paste(sprintf("%.3f",onflagl3), collapse = "     "), con)
  writeLines("onflagl4", con)
  writeLines(paste(sprintf("%.3f",onflagl4), collapse = "     "), con)
  writeLines("offflagu", con)
  writeLines(paste(sprintf("%.3f",offflagu), collapse = "     "), con)
  writeLines("offflagl3", con)
  writeLines(paste(sprintf("%.3f",offflagl3), collapse = "     "), con)
  writeLines("offflagl4", con)
  writeLines(paste(sprintf("%.3f",offflagl4), collapse = "     "), con)
  writeLines("alaiml", con)
  writeLines(paste(sprintf("%.3f",alaiml), collapse = "     "), con)
  writeLines("alaimu", con)
  writeLines(paste(sprintf("%.3f",alaimu), collapse = "     "), con)
  writeLines("cgrass", con)
  writeLines(paste(sprintf("%.3f",cgrass), collapse = "     "), con)
  writeLines("chl", con)
  writeLines(paste(sprintf("%.3f",chl), collapse = "     "), con)
  writeLines("chs", con)
  writeLines(paste(sprintf("%.3f",chs), collapse = "     "), con)
  writeLines("chu", con)
  writeLines(paste(sprintf("%.3f",chu), collapse = "     "), con)
  writeLines("cleaf", con)
  writeLines(paste(sprintf("%.3f",cleaf), collapse = "     "), con)
  writeLines("cstem", con)
  writeLines(paste(sprintf("%.3f",cstem), collapse = "     "), con)
  writeLines("tblowl", con)
  writeLines(paste(sprintf("%.3f",tblowl), collapse = "     "), con)
  writeLines("tblows", con)
  writeLines(paste(sprintf("%.3f",tblows), collapse = "     "), con)
  writeLines("tblowu", con)
  writeLines(paste(sprintf("%.3f",tblowu), collapse = "     "), con)
  writeLines("tdripl", con)
  writeLines(paste(sprintf("%.3f",tdripl), collapse = "     "), con)
  writeLines("tdrips", con)
  writeLines(paste(sprintf("%.3f",tdrips), collapse = "     "), con)
  writeLines("tdripu", con)
  writeLines(paste(sprintf("%.3f",tdripu), collapse = "     "), con)
  writeLines("wliqmin", con)
  writeLines(paste(sprintf("%.3f",wliqmin), collapse = "     "), con)
  writeLines("wliqlmax", con)
  writeLines(paste(sprintf("%.3f",wliqlmax), collapse = "     "), con)
  writeLines("rootr", con)
  writeLines(paste(sprintf("%.3f",rootr), collapse = "     "), con)
  writeLines("wliqsmax", con)
  writeLines(paste(sprintf("%.3f",wliqsmax), collapse = "     "), con)
  writeLines("wliqumax", con)
  writeLines(paste(sprintf("%.3f",wliqumax), collapse = "     "), con)
  writeLines("wsnomin", con)
  writeLines(paste(sprintf("%.3f",wsnomin), collapse = "     "), con)
  writeLines("wsnolmax", con)
  writeLines(paste(sprintf("%.3f",wsnolmax), collapse = "     "), con)
  writeLines("wsnosmax", con)
  writeLines(paste(sprintf("%.3f",wsnosmax), collapse = "     "), con)
  writeLines("wsnoumax", con)
  writeLines(paste(sprintf("%.3f",wsnoumax), collapse = "     "), con)
  writeLines("woodnorm", con)
  writeLines(paste(sprintf("%.3f",woodnorm), collapse = "     "), con)
  writeLines("a11soiltd", con)
  writeLines(paste(sprintf("%.3f",a11soiltd), collapse = "     "), con)
  writeLines("tsoiavg", con)
  writeLines(paste(sprintf("%.3f",tsoiavg), collapse = "     "), con)
  writeLines("Tavgann", con)
  writeLines(paste(sprintf("%.3f",Tavgann), collapse = "     "), con)
  writeLines("PPTavgann", con)
  writeLines(paste(sprintf("%.3f",PPTavgann), collapse = "     "), con)
  writeLines("daylength", con)
  writeLines(paste(sprintf("%.3f",daylength), collapse = "     "), con)
  writeLines("precipsum", con)
  writeLines(paste(sprintf("%.3f",precipsum), collapse = "     "), con)
  writeLines("PPTsumcrit", con)
  writeLines(paste(sprintf("%.3f",PPTsumcrit), collapse = "     "), con)
  writeLines("stsumu", con)
  writeLines(paste(sprintf("%.3f",stsumu), collapse = "     "), con)
  writeLines("stsuml", con)
  writeLines(paste(sprintf("%.3f",stsuml), collapse = "     "), con)
  writeLines("sumcom", con)
  writeLines(paste(sprintf("%.3f",sumcom), collapse = "     "), con)
  writeLines("a3tdmin", con)
  writeLines(paste(sprintf("%.3f",a3tdmin), collapse = "     "), con)
  writeLines("tminavgann", con)
  writeLines(paste(sprintf("%.3f",tminavgann), collapse = "     "), con)
  writeLines("q12", con)
  writeLines(paste(sprintf("%.3f",q12), collapse = "     "), con)
  writeLines("q34", con)
  writeLines(paste(sprintf("%.3f",q34), collapse = "     "), con)
  writeLines("sl", con)
  writeLines(paste(sprintf("%.3f",sl), collapse = "     "), con)
  writeLines("ss", con)
  writeLines(paste(sprintf("%.3f",ss), collapse = "     "), con)
  writeLines("su", con)
  writeLines(paste(sprintf("%.3f",su), collapse = "     "), con)
  writeLines("topparl", con)
  writeLines(paste(sprintf("%.3f",topparl), collapse = "     "), con)
  writeLines("topparu", con)
  writeLines(paste(sprintf("%.3f",topparu), collapse = "     "), con)
  writeLines("tl", con)
  writeLines(paste(sprintf("%.3f",tl), collapse = "     "), con)
  writeLines("ts", con)
  writeLines(paste(sprintf("%.3f",ts), collapse = "     "), con)
  writeLines("tu", con)
  writeLines(paste(sprintf("%.3f",tu), collapse = "     "), con)
  writeLines("tlsub", con)
  writeLines(paste(sprintf("%.3f",tlsub), collapse = "     "), con)
  writeLines("t12", con)
  writeLines(paste(sprintf("%.3f",t12), collapse = "     "), con)
  writeLines("t34", con)
  writeLines(paste(sprintf("%.3f",t34), collapse = "     "), con)
  writeLines("wliql", con)
  writeLines(paste(sprintf("%.3f",wliql), collapse = "     "), con)
  writeLines("wliqs", con)
  writeLines(paste(sprintf("%.3f",wliqs), collapse = "     "), con)
  writeLines("wliqu", con)
  writeLines(paste(sprintf("%.3f",wliqu), collapse = "     "), con)
  writeLines("wsnol", con)
  writeLines(paste(sprintf("%.3f",wsnol), collapse = "     "), con)
  writeLines("wsnos", con)
  writeLines(paste(sprintf("%.3f",wsnos), collapse = "     "), con)
  writeLines("wsnou", con)
  writeLines(paste(sprintf("%.3f",wsnou), collapse = "     "), con)
  writeLines("ci", con)
  writeLines(paste(sprintf("%.3f",ci), collapse = "     "), con)
  writeLines("cs", con)
  writeLines(paste(sprintf("%.3f",cs), collapse = "     "), con)
  writeLines("gs", con)
  writeLines(paste(sprintf("%.3f",gs), collapse = "     "), con)
  writeLines("ag", con)
  writeLines(paste(sprintf("%.3f",ag), collapse = "     "), con)
  # writeLines("an", con)
  # writeLines(paste(sprintf("%.3f",an), collapse = "     "), con)
  writeLines("totcond", con)
  writeLines(paste(sprintf("%.3f",totcond), collapse = "     "), con)
  writeLines("greenfrac", con)
  writeLines(paste(sprintf("%.3f",greenfrac), collapse = "     "), con)
  writeLines("ztopPft", con)
  writeLines(paste(sprintf("%.3f",ztopPft), collapse = "     "), con)
  writeLines("a10anc", con)
  writeLines(paste(sprintf("%.3f",a10anc), collapse = "     "), con)
  writeLines("temp", con)
  writeLines(paste(sprintf("%.3f",temp), collapse = "     "), con)
  writeLines("agddl", con)
  writeLines(paste(sprintf("%.3f",agddl), collapse = "     "), con)
  writeLines("agddu", con)
  writeLines(paste(sprintf("%.3f",agddu), collapse = "     "), con)
  writeLines("fl", con)
  writeLines(paste(sprintf("%.3f",fl), collapse = "     "), con)
  writeLines("fu", con)
  writeLines(paste(sprintf("%.3f",fu), collapse = "     "), con)
  writeLines("templ", con)
  writeLines(paste(sprintf("%.3f",templ), collapse = "     "), con)
  writeLines("dropu", con)
  writeLines(paste(sprintf("%.3f",dropu), collapse = "     "), con)
  writeLines("dropls", con)
  writeLines(paste(sprintf("%.3f",dropls), collapse = "     "), con)
  writeLines("dropl4", con)
  writeLines(paste(sprintf("%.3f",dropl4), collapse = "     "), con)
  writeLines("dropl3", con)
  writeLines(paste(sprintf("%.3f",dropl3), collapse = "     "), con)
  writeLines("gdd0", con)
  writeLines(paste(sprintf("%.3f",gdd0), collapse = "     "), con)
  writeLines("gdd0c", con)
  writeLines(paste(sprintf("%.3f",gdd0c), collapse = "     "), con)
  # writeLines("gdd0this", con)
  # writeLines(paste(sprintf("%.3f",gdd0this), collapse = "     "), con)
  # writeLines("gdd0cthis", con)
  # writeLines(paste(sprintf("%.3f",gdd0cthis), collapse = "     "), con)
  writeLines("gdd5", con)
  writeLines(paste(sprintf("%.3f",gdd5), collapse = "     "), con)
  # writeLines("gdd5this", con)
  # writeLines(paste(sprintf("%.3f",gdd5this), collapse = "     "), con)
  # writeLines("gdd8", con)
  # writeLines(paste(sprintf("%.3f",gdd8), collapse = "     "), con)
  # writeLines("gdd10", con)
  # writeLines(paste(sprintf("%.3f",gdd10), collapse = "     "), con)
  # writeLines("gdd12", con)
  # writeLines(paste(sprintf("%.3f",gdd12), collapse = "     "), con)
  # writeLines("gdd8this", con)
  # writeLines(paste(sprintf("%.3f",gdd8this), collapse = "     "), con)
  # writeLines("gdd10this", con)
  # writeLines(paste(sprintf("%.3f",gdd10this), collapse = "     "), con)
  # writeLines("gdd12this", con)
  # writeLines(paste(sprintf("%.3f",gdd12this), collapse = "     "), con)
  writeLines("sapfrac", con)
  writeLines(paste(sprintf("%.3f",sapfrac), collapse = "     "), con)
  writeLines("tc", con)
  writeLines(paste(sprintf("%.3f",tc), collapse = "     "), con)
  # writeLines("tcthis", con)
  # writeLines(paste(sprintf("%.3f",tcthis), collapse = "     "), con)
  writeLines("tcmin", con)
  writeLines(paste(sprintf("%.3f",tcmin), collapse = "     "), con)
  writeLines("totlail", con)
  writeLines(paste(sprintf("%.3f",totlail), collapse = "     "), con)
  writeLines("totlaiu", con)
  writeLines(paste(sprintf("%.3f",totlaiu), collapse = "     "), con)
  writeLines("totbiol", con)
  writeLines(paste(sprintf("%.3f",totbiol), collapse = "     "), con)
  writeLines("totbiou", con)
  writeLines(paste(sprintf("%.3f",totbiou), collapse = "     "), con)
  writeLines("tw", con)
  writeLines(paste(sprintf("%.3f",tw), collapse = "     "), con)
  # writeLines("twthis", con)
  # writeLines(paste(sprintf("%.3f",twthis), collapse = "     "), con)
  writeLines("disturbf", con)
  writeLines(paste(sprintf("%.3f",disturbf), collapse = "     "), con)
  writeLines("disturbo", con)
  writeLines(paste(sprintf("%.3f",disturbo), collapse = "     "), con)
  writeLines("firefac", con)
  writeLines(paste(sprintf("%.3f",firefac), collapse = "     "), con)
  writeLines("tco2mic", con)
  writeLines(paste(sprintf("%.3f",tco2mic), collapse = "     "), con)
  writeLines("tco2root", con)
  writeLines(paste(sprintf("%.3f",tco2root), collapse = "     "), con)
  writeLines("tneetot", con)
  writeLines(paste(sprintf("%.3f",tneetot), collapse = "     "), con)
  writeLines("tnmin", con)
  writeLines(paste(sprintf("%.3f",tnmin), collapse = "     "), con)
  writeLines("tnpptot", con)
  writeLines(paste(sprintf("%.3f",tnpptot), collapse = "     "), con)
  writeLines("tgpptot", con)
  writeLines(paste(sprintf("%.3f",tgpptot), collapse = "     "), con)
  writeLines("totalit", con)
  writeLines(paste(sprintf("%.3f",totalit), collapse = "     "), con)
  writeLines("totanlit", con)
  writeLines(paste(sprintf("%.3f",totanlit), collapse = "     "), con)
  writeLines("totcmic", con)
  writeLines(paste(sprintf("%.3f",totcmic), collapse = "     "), con)
  writeLines("totcsoi", con)
  writeLines(paste(sprintf("%.3f",totcsoi), collapse = "     "), con)
  writeLines("totfall", con)
  writeLines(paste(sprintf("%.3f",totfall), collapse = "     "), con)
  writeLines("totlit", con)
  writeLines(paste(sprintf("%.3f",totlit), collapse = "     "), con)
  writeLines("totnlit", con)
  writeLines(paste(sprintf("%.3f",totnlit), collapse = "     "), con)
  writeLines("totnmic", con)
  writeLines(paste(sprintf("%.3f",totnmic), collapse = "     "), con)
  writeLines("totnsoi", con)
  writeLines(paste(sprintf("%.3f",totnsoi), collapse = "     "), con)
  writeLines("totrlit", con)
  writeLines(paste(sprintf("%.3f",totrlit), collapse = "     "), con)
  writeLines("totrnlit", con)
  writeLines(paste(sprintf("%.3f",totrnlit), collapse = "     "), con)
  writeLines("tempu", con)
  writeLines(paste(sprintf("%.3f",tempu), collapse = "     "), con)
  writeLines("templs", con)
  writeLines(paste(sprintf("%.3f",templs), collapse = "     "), con)
  writeLines("greenfracl", con)
  writeLines(paste(sprintf("%.3f",greenfracl), collapse = "     "), con)
  writeLines("greenfracl3", con)
  writeLines(paste(sprintf("%.3f",greenfracl3), collapse = "     "), con)
  writeLines("greenfracl4", con)
  writeLines(paste(sprintf("%.3f",greenfracl4), collapse = "     "), con)
  writeLines("vegtype0", con)
  writeLines(paste(sprintf("%.3f",vegtype0), collapse = "     "), con)
  writeLines("cbiol", con)
  writeLines(paste(sprintf("%.3f",cbiol), collapse = "     "), con)
  writeLines("cbior", con)
  writeLines(paste(sprintf("%.3f",cbior), collapse = "     "), con)
  writeLines("cbiow", con)
  writeLines(paste(sprintf("%.3f",cbiow), collapse = "     "), con)
  writeLines("cbiog", con)
  writeLines(paste(sprintf("%.3f",cbiog), collapse = "     "), con)
  writeLines("cbios", con)
  writeLines(paste(sprintf("%.3f",cbios), collapse = "     "), con)
  writeLines("clitll", con)
  writeLines(paste(sprintf("%.3f",clitll), collapse = "     "), con)
  writeLines("clitlm", con)
  writeLines(paste(sprintf("%.3f",clitlm), collapse = "     "), con)
  writeLines("clitls", con)
  writeLines(paste(sprintf("%.3f",clitls), collapse = "     "), con)
  writeLines("clitrl", con)
  writeLines(paste(sprintf("%.3f",clitrl), collapse = "     "), con)
  writeLines("clitrm", con)
  writeLines(paste(sprintf("%.3f",clitrm), collapse = "     "), con)
  writeLines("clitrs", con)
  writeLines(paste(sprintf("%.3f",clitrs), collapse = "     "), con)
  writeLines("clitwl", con)
  writeLines(paste(sprintf("%.3f",clitwl), collapse = "     "), con)
  writeLines("clitwm", con)
  writeLines(paste(sprintf("%.3f",clitwm), collapse = "     "), con)
  writeLines("clitws", con)
  writeLines(paste(sprintf("%.3f",clitws), collapse = "     "), con)
  writeLines("csoipas", con)
  writeLines(paste(sprintf("%.3f",csoipas), collapse = "     "), con)
  writeLines("csoislo", con)
  writeLines(paste(sprintf("%.3f",csoislo), collapse = "     "), con)
  writeLines("csoislon", con)
  writeLines(paste(sprintf("%.3f",csoislon), collapse = "     "), con)
  writeLines("csoislop", con)
  writeLines(paste(sprintf("%.3f",csoislop), collapse = "     "), con)
  writeLines("decompl", con)
  writeLines(paste(sprintf("%.3f",decompl), collapse = "     "), con)
  writeLines("decomps", con)
  writeLines(paste(sprintf("%.3f",decomps), collapse = "     "), con)
  writeLines("falll", con)
  writeLines(paste(sprintf("%.3f",falll), collapse = "     "), con)
  writeLines("falllsgc", con)
  writeLines(paste(sprintf("%.3f",falllsgc), collapse = "     "), con)
  writeLines("fallr", con)
  writeLines(paste(sprintf("%.3f",fallr), collapse = "     "), con)
  writeLines("fallrsgc", con)
  writeLines(paste(sprintf("%.3f",fallrsgc), collapse = "     "), con)
  writeLines("fallw", con)
  writeLines(paste(sprintf("%.3f",fallw), collapse = "     "), con)
  writeLines("cdisturb", con)
  writeLines(paste(sprintf("%.3f",cdisturb), collapse = "     "), con)
  writeLines("biomass", con)
  writeLines(paste(sprintf("%.3f",biomass), collapse = "     "), con)
  writeLines("frac", con)
  writeLines(paste(sprintf("%.3f",frac), collapse = "     "), con)
  writeLines("plai", con)
  writeLines(paste(sprintf("%.3f",plai), collapse = "     "), con)
  writeLines("plaimx", con)
  writeLines(paste(sprintf("%.3f",plaimx), collapse = "     "), con)
  writeLines("tnpp", con)
  writeLines(paste(sprintf("%.3f",tnpp), collapse = "     "), con)
  writeLines("tgpp", con)
  writeLines(paste(sprintf("%.3f",tgpp), collapse = "     "), con)
  writeLines("nppdummy", con)
  writeLines(paste(sprintf("%.3f",nppdummy), collapse = "     "), con)
  writeLines("lai", con)
  writeLines(paste(sprintf("%.3f",lai), collapse = "     "), con)
  writeLines("sai", con)
  writeLines(paste(sprintf("%.3f",sai), collapse = "     "), con)
  writeLines("zbot", con)
  writeLines(paste(sprintf("%.3f",zbot), collapse = "     "), con)
  writeLines("ztop", con)
  writeLines(paste(sprintf("%.3f",ztop), collapse = "     "), con)
  writeLines("ztopmx", con)
  writeLines(paste(sprintf("%.3f",ztopmx), collapse = "     "), con)
  writeLines("htmx", con)
  writeLines(paste(sprintf("%.3f",htmx), collapse = "     "), con)
  writeLines("dleaf", con)
  writeLines(paste(sprintf("%.3f",dleaf), collapse = "     "), con)
  writeLines("dstem", con)
  writeLines(paste(sprintf("%.3f",dstem), collapse = "     "), con)
  writeLines("orieh", con)
  writeLines(paste(sprintf("%.3f",orieh), collapse = "     "), con)
  writeLines("oriev", con)
  writeLines(paste(sprintf("%.3f",oriev), collapse = "     "), con)
  writeLines("rhoveg", con)
  writeLines(paste(sprintf("%.3f",rhoveg), collapse = "     "), con)
  writeLines("tauveg", con)
  writeLines(paste(sprintf("%.3f",tauveg), collapse = "     "), con)
  writeLines("froot", con)
  writeLines(paste(sprintf("%.3f",froot), collapse = "     "), con)
  writeLines("exist", con)
  writeLines(paste(sprintf("%.3f",exist), collapse = "     "), con)
  writeLines("use", con)
  writeLines(paste(sprintf("%.3f",use), collapse = "     "), con)
  writeLines("specla", con)
  writeLines(paste(sprintf("%.3f",specla), collapse = "     "), con)
  writeLines("aleaf", con)
  writeLines(paste(sprintf("%.3f",aleaf), collapse = "     "), con)
  writeLines("aroot", con)
  writeLines(paste(sprintf("%.3f",aroot), collapse = "     "), con)
  writeLines("awood", con)
  writeLines(paste(sprintf("%.3f",awood), collapse = "     "), con)
  writeLines("lonindex", con)
  writeLines(paste(sprintf("%.3f",lonindex), collapse = "     "), con)
  writeLines("latindex", con)
  writeLines(paste(sprintf("%.3f",latindex), collapse = "     "), con)
  close(con)
}
